# turkish language definition
ICON_KEY									"key.png"
ICON_NO_KEY									"nokey.png"
STRING_WELCOME								"Hoşgeldiniz"
STRING_ENTER_PASSPHRASE						"Şifrenizi girin"
STRING_PASSPHRASE							"Şifre"
STRING_OK									"Tamam"
STRING_EXIT									"Çık"
STRING_ADDRESSBOOK							"Rehber"
STRING_DELETE_ADDRESS						"Adresi sil"
STRING_KEY_LIST								"Alınan kodlar"
STRING_IMPORT_KEY_FROM_RECEIVED				"Mesajdan kodu ithal et"
STRING_GENERATING_KEYPAIR					"Kod çifti üretmek ..."
STRING_BACK									"Geri"
STRING_PUBLIC_KEYS							"Mevcut kodlar"
STRING_DELETE_KEY							"Kodu sil"
STRING_NO_KEY_FOR_SENDER					"Kod bulunamadı"
STRING_SEND_MESSAGE							"Mesaj gönder"
STRING_ADDRESS_CHOICE						"İsim seçimim"
STRING_SELECT_PLEASE						"İsim seçenek"
STRING_YOUR_NAME							"İsminiz"
STRING_YOUR_NUMBER							"Telefon numaranız"
STRING_NEW_ENTRY							"Yeni kayıt"
STRING_EDIT_ENTRY							"Kayıdı işle"
STRING_NEW_MESSAGE							"Yeni mesaj"
STRING_NO_MESSAGEBOX						"Mesaj yok"
STRING_SEND_PUBKEY							"Kodu gönder (kodlanmamış)" 
STRING_NUMBER_WITH_SPACES					" Numara: "
STRING_KEY_1								"Kod"
STRING_CANCEL								"İptal"
STRING_ERROR_ONLY_ENCRYPTED_SENDING			"Sadece kodu mevcut kişilere mesaj gönderilebilir!"
STRING_CHANGE_NAME							"İsmi değiştir"
STRING_NAME									"İsim"
STRING_NUMBER								"Numara: "
STRING_MESSAGE								"Mesaj: "
STRING_NEW_SMS								"Mesaj oluştur"
STRING_INBOX								"Gelen kutusu"
STRING_OUTBOX								"Gönderilmiş mesajlar"
STRING_CLEAR_MEMORY							"Kayıtları sil"
STRING_MENU									"Menü"
STRING_TEXT									"Metin"
STRING_SENDING_MESSAGE						"Mesaj gönder"
STRING_VIEW_MESSAGE							"Mesaja bakın"
STRING_IMPORT_KEY							"Kodu ithal et" 
STRING_DELETE_MESSAGE						"Mesaji sil"
STRING_MESSAGE_TYPE							"Tip: “
STRING_FORM_INCOMPLETE						"Eksik alanlar!"
STRING_ENCRYPT_MESSAGE						"Mesaj kodlanıyor..." 
STRING_DECRYPT_MESSAGE						"Mesaj deşifre ediliyor..." 
STRING_ERROR_WRONG_TYPE						" Yalnızca metin mesajları (birinci tip)görüntülenebilir!" 
STRING_ERROR_WRONG_TYPE2					" Yalnızca kodlar (üçüncü Tipp) ithal edilebilir!" 
STRING_INITIALIZATION						"Başlatma" 
STRING_YOUR_NUMBER							"Telefon numaranız: "
STRING_ERROR_THREAD							"Thread başlatılmasında hata var: "
STRING_ERROR_MESSAGE_RECEIVE				"Mesajın alınmasında hata: "
STRING_NEW_MESSAGE_RECEIVED					"Yeni mesaj tarafından " 
STRING_ERROR_MESSAGE_RECEIVE2				"Mesaj alınamadı: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS		"Adresin silinmesi başarılamadı"
STRING_ERROR_DELETE_MESSAGE					"Mesajın silinmesi başarılamadı " 
STRING_ERROR_PERSON_ALREADY_EXISTS			"Kişi ismi rehberde var"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS		"Bu numaraya uyan kişi kaydedildi"
STRING_ERROR_SAVING_MESSAGE_FAILED			"Mesaj kaydedilemedi: "
STRING_ERROR_LOADING_SETTINGS_FAILED		"Ayarları yükle başarılamadı: "
STRING_ERROR_OPEN_SETTINGS					"Ayarların açması başarılamadı: "
STRING_ERROR_SAVE_SETTINGS					"Ayarları kaydetmesi başarılamadı: "
STRING_ERROR_NO_PERSON_WITH_NUMBER			"Numaraya uyan kişi yok: "
STRING_ADDED_KEY_TO_PERSON					"Şifre bu numaradaki kişiye eklendi: "
STRING_RETURN_PASSPHRASE					"Şifreyi onaylayın"
STRING_FORM_NAME_MIN_2_CHARS				"İsim en az 2 işaretten oluşmalı!"
STRING_FORM_NUMBER_MIN_7_CHARS				" Numara en az 7 sayıdan oluşmalı!"
STRING_FORM_PASS_MIN_5_CHARS				" Şifre en az 5 işaretten oluşmalı!"
STRING_FORM_PASS_NOT_MATCH_REPEAT 			"İlk ve ikinci şifre girişi aynı değil!"
STRING_FORM_PASS_NOT_MATCH					"Yalnış şifre!"
STRING_READ_INBOX							"Gelen kutusu"
STRING_UNREAD_INBOX							"Yeni mesajler"
STRING_ERROR_DECRYPT						"Error during decryption: "
STRING_INFO									"Info"
STRING_VERSION								"Version: "
STRING_BUILD								"Build: "
STRING_REPLY								"Cevap"
STRING_NEW_MESSAGES_RECEIVED				"Yeni mesaj tarafından"
