/*
 * Generated by XDoclet - Do not edit!
 */
package zoo;

/**
 * Home interface for Tiger.
 * @generated 
 * @wtp generated
 */
public interface TigerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Tiger";
   public static final String JNDI_NAME="Tiger";

   public zoo.Tiger create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
