/*
 * Generated by XDoclet - Do not edit!
 */
package zoo;

/**
 * Local home interface for Tiger.
 * @generated 
 * @wtp generated
 */
public interface TigerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TigerLocal";
   public static final String JNDI_NAME="TigerLocal";

   public zoo.TigerLocal create()
      throws javax.ejb.CreateException;

}
