/*
 * Generated by XDoclet - Do not edit!
 */
package zoo;

/**
 * Remote interface for Tiger.
 * @generated 
 * @wtp generated
 */
public interface Tiger
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String leone(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String cane(  )
      throws java.rmi.RemoteException;

}
