# spanish language definition
ICON_KEY							"key.png"
ICON_NO_KEY							"nokey.png"
STRING_WELCOME						"Bienvenidos!"
STRING_ENTER_PASSPHRASE				"Digíte su Clave"
STRING_PASSPHRASE					"Clave:"
STRING_OK							"OK"
STRING_EXIT							"Abandonar"
STRING_ADDRESSBOOK					"Directorio"
STRING_DELETE_ADDRESS				"Borrar Dirección"
STRING_KEY_LIST						"Código Recibido"
STRING_IMPORT_KEY_FROM_RECEIVED		"Importar Código de un Mensaje"
STRING_GENERATING_KEYPAIR			"Generar Código Dual..."
STRING_BACK							"Regresar"
STRING_PUBLIC_KEYS					"Código Existente"
STRING_DELETE_KEY					"Borrar Código"
STRING_NO_KEY_FOR_SENDER			"Ningun Código Existente"
STRING_SEND_MESSAGE					"Enviar Mensaje"
STRING_ADDRESS_CHOICE				"Seleccion de Direcciones"
STRING_SELECT_PLEASE				"Seleccionar Dirección"
STRING_YOUR_NAME					"Su Nombre"
STRING_YOUR_NUMBER					"Su Número Telefónico"
STRING_NEW_ENTRY					"Nueva Entrada"
STRING_EDIT_ENTRY					"Cambiar Entrada"
STRING_NEW_MESSAGE					"Escribir Mensaje"
STRING_NO_MESSAGEBOX				"Ningún Mensaje"
STRING_SEND_PUBKEY					"Enviar Código (Decodificado)"
STRING_NUMBER_WITH_SPACES			" Número: "
STRING_KEY_1						" Código "
STRING_CANCEL						"Cancelar"
STRING_ERROR_ONLY_ENCRYPTED_SENDING	"Sólo Se Pueden Enviar Mensajes a Personas Cuyo Código Está Disponible!"
STRING_CHANGE_NAME					"Cambiar Nombre"
STRING_NAME							"Nombre:"
STRING_NUMBER						"Número:"
STRING_MESSAGE						"Mensaje:"
STRING_NEW_SMS						"Originar Nuevo Mensaje"
STRING_INBOX						"Entrada"
STRING_OUTBOX						"Enviado"
STRING_CLEAR_MEMORY					"Borrar Memoria"
STRING_MENU							"Menú"
STRING_TEXT							"Texto"
STRING_SENDING_MESSAGE				"Enviar Mensaje "
STRING_VIEW_MESSAGE					"Ver Mensaje"
STRING_IMPORT_KEY					"Importar Código"
STRING_DELETE_MESSAGE				"Borrar Mensaje"
STRING_MESSAGE_TYPE					"Tipo de Mensaje:"
STRING_FORM_INCOMPLETE				"Espacios Incompletos!"
STRING_ENCRYPT_MESSAGE				"Mensaje Códificado..."
STRING_DECRYPT_MESSAGE				"Mensaje Decodificado..."
STRING_ERROR_WRONG_TYPE				" Sólo Mensajes de Texto (Tipo 1) Pueden Ser Mostrados!"
STRING_ERROR_WRONG_TYPE2			" Sólo Se Pueden Importar Códigos (Tipo 3)!"
STRING_INITIALIZATION				"Inicialización"
STRING_YOUR_NUMBER					"Su Número Telefónico:"
STRING_ERROR_THREAD					"Error al Iniciar Thread: "
STRING_ERROR_MESSAGE_RECEIVE		"Error al Recibir Mensaje: "
STRING_NEW_MESSAGE_RECEIVED			"Nuevo Mensaje Recibido"
STRING_ERROR_MESSAGE_RECEIVE2		"El Mensaje No Pudo Ser Recibido: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS	"Falla Al Borrar Dirección"
STRING_ERROR_DELETE_MESSAGE			"Falla Al Borrar Mensaje"
STRING_ERROR_PERSON_ALREADY_EXISTS	"Persona Ya Existente En El Directorio"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS	"Persona Con Ese Nombre Ya Ha Sido Introducida"
STRING_ERROR_SAVING_MESSAGE_FAILED	"El Mensaje No Se Pudo Archivar: "
STRING_ERROR_LOADING_SETTINGS_FAILED	"Falla Al Descargar Los Ajustes: "
STRING_ERROR_OPEN_SETTINGS			"Falla Al Abrir Los Ajustes: "
STRING_ERROR_SAVE_SETTINGS			"Falla Al Archivar Los Ajustes: "
STRING_ERROR_NO_PERSON_WITH_NUMBER	"No Se Encontró Nínguna Persona Con Ese Número: "
STRING_ADDED_KEY_TO_PERSON			"Se Le Ha Agregado Un Código A La Persona Con Ese Número: "
STRING_RETURN_PASSPHRASE			"Confirmar Clave"
STRING_FORM_NAME_MIN_2_CHARS		"El Nombre Debe Constar De Como Mínimo 2 Letras!"
STRING_FORM_NUMBER_MIN_7_CHARS		"El Número Telefónico Debe Constar De Como Mínimo 7 Cifras!"
STRING_FORM_PASS_MIN_5_CHARS		"La Clave Debe Constar De Como Mínimo 5 Letras!"
STRING_FORM_PASS_NOT_MATCH_REPEAT	"Primera Y Segunda Clave Digitada No Son Idénticas!"
STRING_FORM_PASS_NOT_MATCH			"Clave Equivocada!"
STRING_READ_INBOX					"Viejo Mensajes"
STRING_UNREAD_INBOX					"Nuevo Mensajes"
STRING_ERROR_DECRYPT				"Error Al Decodificar: "
STRING_INFO							"Info"
STRING_VERSION						"Version: "
STRING_BUILD						"Build: "
STRING_REPLY						"Contestar"
STRING_NEW_MESSAGES_RECEIVED		"Nuevo Mensaje Recibido"
