# polish language definition
ICON_KEY								"key.png"
ICON_NO_KEY								"nokey.png"
STRING_WELCOME							"cześć!"
STRING_ENTER_PASSPHRASE					"Podaj hasło"
STRING_PASSPHRASE						"Hasło:"
STRING_OK								"OK"
STRING_EXIT								"Opuść"
STRING_ADDRESSBOOK						"Książka adresowa"
STRING_DELETE_ADDRESS					"Usuń adres"
STRING_KEY_LIST							"Odebrane klucze"
STRING_IMPORT_KEY_FROM_RECEIVED			"Importuj klucz z wiadomości"
STRING_GENERATING_KEYPAIR				"Generuje klucze..."
STRING_BACK								"Wróć"
STRING_PUBLIC_KEYS						"Dostępne klucze"
STRING_DELETE_KEY						"Usuń klucz"
STRING_NO_KEY_FOR_SENDER				"Brak klucza"
STRING_SEND_MESSAGE						"Wyślij wiadomość"
STRING_ADDRESS_CHOICE					"Wybór adresu"
STRING_SELECT_PLEASE					"Wybierz adres"
STRING_YOUR_NAME						"Twoje Imię"
STRING_YOUR_NUMBER						"Twój numer telefoniczny"
STRING_NEW_ENTRY						"Nowy wpis"
STRING_EDIT_ENTRY						"Zmień wpis"
STRING_NEW_MESSAGE						"Nowa wiadomość"
STRING_NO_MESSAGEBOX					"Brak wiadomości"
STRING_SEND_PUBKEY						"Wyślij klucz (niezaszyfrowany)"
STRING_NUMBER_WITH_SPACES				" Numer: "
STRING_KEY_1							"Klucz "
STRING_CANCEL							"Skasuj"
STRING_ERROR_ONLY_ENCRYPTED_SENDING		"SMS-y mogą być wysłane tylko do osób, które posiadają klucz!"
STRING_CHANGE_NAME						"Zmień imię"
STRING_NAME								"Imię:"
STRING_NUMBER							"Numer:"
STRING_MESSAGE							"Wiadomość:"
STRING_NEW_SMS							"Nowy SMS"
STRING_INBOX							"Wejdź"
STRING_OUTBOX							"Wysłane"
STRING_CLEAR_MEMORY						"Wyczyść pamięć"
STRING_MENU								"Menu"
STRING_TEXT								"Tekst"
STRING_SENDING_MESSAGE					"Wyślij wiadomość "
STRING_VIEW_MESSAGE						"Zobacz wiadomość"
STRING_IMPORT_KEY						"Importuj klucz"
STRING_DELETE_MESSAGE					"Usuń wiadomość"
STRING_MESSAGE_TYPE						"Typ: "
STRING_FORM_INCOMPLETE					"Pole niewypełnione!"
STRING_ENCRYPT_MESSAGE					"szyfruje wiadomość..."
STRING_DECRYPT_MESSAGE					"deszyfruje wiadomość..."
STRING_ERROR_WRONG_TYPE					" Tylko wiadomości tekstowe (Typ 1) mogą być pokazane!"
STRING_ERROR_WRONG_TYPE2				" Tylko klucze (Typu 3) mgą być importowane!"
STRING_INITIALIZATION					"Inicjacja"
STRING_YOUR_NUMBER						"Twój numer telefonu:"
STRING_ERROR_THREAD						"Wystąpił błąd przy starcie Thread: "
STRING_ERROR_MESSAGE_RECEIVE			" Błąd przy odbiorze wiadomości: "
STRING_NEW_MESSAGE_RECEIVED				"Nowa wiadomość od "
STRING_ERROR_MESSAGE_RECEIVE2			"Wiadomość nie mogła zostać odebrana: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS	"Błąd przy usuwaniu adresu"
STRING_ERROR_DELETE_MESSAGE				"Błąd przy usuwaniu wiadomości"
STRING_ERROR_PERSON_ALREADY_EXISTS		"Błąd - osoba jest już w spisie adresów"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS "Osoba o tym imieniu jest już w spisie adresów"
STRING_ERROR_SAVING_MESSAGE_FAILED		"Błąd - wiadomość nie została zapisana: "
STRING_ERROR_LOADING_SETTINGS_FAILED	"Błąd - Laden der Settings fehlgeschlagen: "
STRING_ERROR_OPEN_SETTINGS				"Błąd - otwarcie ustawień niemożliwe: "
STRING_ERROR_SAVE_SETTINGS				"Błąd - zapis ustawień niemożliwy: "
STRING_ERROR_NO_PERSON_WITH_NUMBER		"Błąd - osoba z tym numerem nie została znaleziona: "
STRING_ADDED_KEY_TO_PERSON				"Klucz został przypisany osbie z tym numerem: "
STRING_RETURN_PASSPHRASE				"Potwierdź hasło"
STRING_FORM_NAME_MIN_2_CHARS			"Imię musi mieć co najmniej 2 znaki!"
STRING_FORM_NUMBER_MIN_7_CHARS			"Numer telefonu musi mieć co najmniej 7 cyfr!"
STRING_FORM_PASS_MIN_5_CHARS			"Hasło musi mieć co najmniej 5 znaków!"
STRING_FORM_PASS_NOT_MATCH_REPEAT		 "1. i 2. hasło nie są identyczne!"
STRING_FORM_PASS_NOT_MATCH				"Niewłaściwe hasło!"
STRING_READ_INBOX						"Wejdź"
STRING_UNREAD_INBOX						"Nowa wiadomość"
STRING_ERROR_DECRYPT					"Error during decryption: "
STRING_INFO								"Info"
STRING_VERSION							"Version: "
STRING_BUILD							"Build: "
STRING_REPLY							"Odpyskowywać"
STRING_NEW_MESSAGES_RECEIVED			"Nowa wiadomość"
