# italian language definition
ICON_KEY									"key.png"
ICON_NO_KEY									"nokey.png"
STRING_WELCOME								"Benvenuto/a!"
STRING_ENTER_PASSPHRASE						"Inserire la passphrase"
STRING_PASSPHRASE							"Passphrase:"
STRING_OK									"Ok"
STRING_EXIT									"Esci"
STRING_ADDRESSBOOK							"Rubrica"
STRING_DELETE_ADDRESS						"Elimina indirizzo"
STRING_KEY_LIST								"Chiavi ricevute"
STRING_IMPORT_KEY_FROM_RECEIVED				"Importa la chiave dal messaggio"
STRING_GENERATING_KEYPAIR					"Generazione della coppia di chiavi ..."
STRING_BACK									"Indietro"
STRING_PUBLIC_KEYS							"Chiavi pubbliche"
STRING_DELETE_KEY							"Cancella la chiave"
STRING_NO_KEY_FOR_SENDER					"Nessuna chiave per il mittente"
STRING_SEND_MESSAGE							"Invia il messaggio"
STRING_ADDRESS_CHOICE						"Selezione indirizzo"
STRING_SELECT_PLEASE						"Seleziona un indirizzo"
STRING_YOUR_NAME							"Il tuo nome"
STRING_YOUR_NUMBER							"Il tuo numero di telefono"
STRING_SMSC_GSM_NUMBER						"Numero di telefono CGSS"
STRING_NEW_ENTRY							"Nuovo inserimento"
STRING_EDIT_ENTRY							"Modifica"
STRING_NEW_MESSAGE							"Scrivi messaggio"
STRING_NO_MESSAGEBOX						"Nessun messaggio"
STRING_SEND_PUBKEY							"Invia la chiave (decifrata)"
STRING_NUMBER_WITH_SPACES					" numero: "
STRING_KEY_1								" chiave "
STRING_CANCEL								"Annulla"
STRING_ERROR_ONLY_ENCRYPTED_SENDING			"Possono essere inviati messaggi solo a persone di cui si possiede la chiave!"
STRING_CHANGE_NAME							"Cambia nome"
STRING_NAME									"Nome:"
STRING_NUMBER								"Numero:"
STRING_MESSAGE								"Messaggio:"
STRING_NEW_SMS								"Crea un nuovo messaggio"
STRING_INBOX								"Messaggi in arrivo"
STRING_OUTBOX								"Messaggi inviati"
STRING_CLEAR_MEMORY							"Cancella memoria"
STRING_MENU									"Menu"
STRING_TEXT									"Testo"
STRING_SENDING_MESSAGE						"Invia messaggio "
STRING_VIEW_MESSAGE							"Mostra messaggio"
STRING_IMPORT_KEY							"Importa la chiave"
STRING_DELETE_MESSAGE						"Elimina il messaggio"
STRING_MESSAGE_TYPE							"Tipo di messaggio:"
STRING_FORM_INCOMPLETE						"Campi incompleti!"
STRING_ENCRYPT_MESSAGE						"Cifro il messaggio..."
STRING_DECRYPT_MESSAGE						"Decifro messaggio..."
STRING_ERROR_WRONG_TYPE						" errore: solo i messaggi di testo (tipo 1)possono essere visualizzati!"
STRING_ERROR_WRONG_TYPE2					" errore: solo le chiavi (tipo 3) possono essere importate!"
STRING_INITIALIZATION						"Inizializzazione"
STRING_YOUR_NUMBER							"Il tuo numero di telefono:"
STRING_ERROR_THREAD							"Errore nell'avviare il thread: "
STRING_ERROR_MESSAGE_RECEIVE				"Errore nella ricezione del messaggio: "
STRING_NEW_MESSAGE_RECEIVED					"Nuovo messaggio ricevuto da "
STRING_ERROR_MESSAGE_RECEIVE2				"Errore nella ricezione del messaggio: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS		"Errore nell' eliminazione indirizzo"
STRING_ERROR_DELETE_MESSAGE					"Errore nell' eliminazione messaggio"
STRING_ERROR_PERSON_ALREADY_EXISTS			"Persona già esistente in rubbrica"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS	"Una persona con questo nome e già esistente"
STRING_ERROR_SAVING_MESSAGE_FAILED			"Errore nel salvare il messaggio: "
STRING_ERROR_LOADING_SETTINGS_FAILED		"Errore nel caricare i settaggi: "
STRING_ERROR_OPEN_SETTINGS					"Errore nell'aprire i settaggi: "
STRING_ERROR_SAVE_SETTINGS					"Errore nel salvare i settings: "
STRING_ERROR_NO_PERSON_WITH_NUMBER			"Errore nel trovare la persona con questo numero: "
STRING_ADDED_KEY_TO_PERSON					"Chiave aggiunta alla persona con questo numero: "
STRING_RETURN_PASSPHRASE					"Conferma passphrase"
STRING_FORM_NAME_MIN_2_CHARS				"Il nome deve comprendere minimo 2 caratteri!"
STRING_FORM_NUMBER_MIN_7_CHARS				"Il numero di telefono deve comprendere minimo 7 cifre!"
STRING_FORM_PASS_MIN_5_CHARS				"La passphrase deve comprendere minimo 5 caratteri!"
STRING_FORM_PASS_NOT_MATCH_REPEAT			"1o e 2o inserimento della passphrase non identici!"
STRING_FORM_PASS_NOT_MATCH					"Passphrase errata!"
STRING_READ_INBOX							"Messaggi letti"
STRING_UNREAD_INBOX							"Messaggi nuovi"
STRING_ERROR_DECRYPT						"Errore nel decifrare: "
STRING_INFO									"Info"
STRING_VERSION								"Version: "
STRING_BUILD								"Build: "
STRING_REPLY								"Rispondi"
STRING_NEW_MESSAGES_RECEIVED				"Nuovo messaggio ricevuto"
