# french language definition
ICON_KEY								"key.png"
ICON_NO_KEY								"nokey.png"
STRING_WELCOME							"Bienvenue !"
STRING_ENTER_PASSPHRASE					"Enter votre phrase secrète"
STRING_PASSPHRASE						"Mot de passe:"
STRING_OK								"OK"
STRING_EXIT								"QUITTER"
STRING_ADDRESSBOOK						"Carnet d'adresses"
STRING_DELETE_ADDRESS 					"Supprimer l'adresse"
STRING_KEY_LIST							"Clés Reçues"
STRING_GENERATING_KEYPAIR				"Génération de la paire de clés..."
STRING_PUBLIC_KEYS						"Clés publiques sur le système"
STRING_BACK								"Retour"
STRING_YOUR_NAME						"Votre nom"
STRING_YOUR_NUMBER						"Votre numéro de téléphone"
STRING_NEW_ENTRY						"Nouvelle entrée"
STRING_EDIT_ENTRY						"Modifier l'entrée"
STRING_NEW_MESSAGE						"Nouveau message"
STRING_SEND_PUBKEY						"Envoyer une clé publique (sans chiffrement)"
STRING_NUMBER_WITH_SPACES				" numéro : "
STRING_KEY_1							" clé "
STRING_CANCEL							"Annuler"
STRING_ERROR_ONLY_ENCRYPTED_SENDING		"Vous ne pouvez envoyer un SMS que si vous avez la clé publique de votre destinataire !"
STRING_CHANGE_NAME						"Changer le nom"
STRING_NAME								"Nom :"
STRING_NUMBER							"Numéro :"
STRING_MESSAGE							"Message :"
STRING_NEW_SMS							"Ecrire un SMS"
STRING_INBOX							"Boite de réception"
STRING_OUTBOX							"Messages envoyés"
STRING_CLEAR_MEMORY						"Vider la mémoire"
STRING_MENU								"Menu"
STRING_TEXT								"Texte"
STRING_SENDING_MESSAGE					"Envoi du message "
STRING_VIEW_MESSAGE						"Voir le message"
STRING_IMPORT_KEY						"Importer une clé"
STRING_IMPORT_KEY_FROM_RECEIVED			"Importer une clé d'un message"
STRING_DELETE_KEY						"Supprimer la clé"
STRING_NO_KEY_FOR_SENDER				"Clé manquante"
STRING_ADDRESS_CHOICE					"Choisir une adresse"
STRING_SEND_MESSAGE						"Envoyer le message"
STRING_NO_MESSAGEBOX					"Pas de boite de messages"
STRING_SELECT_PLEASE					"Choisir une adresse"
STRING_DELETE_MESSAGE					"Supprimer un message"
STRING_MESSAGE_TYPE						"Type :"
STRING_FORM_INCOMPLETE					"Entrée invalide !"
STRING_ENCRYPT_MESSAGE					"Chiffrement du message ..."
STRING_DECRYPT_MESSAGE					"Déchiffrement du message ..."
STRING_ERROR_WRONG_TYPE1				" Seulement les messages textes (Type 1) sont affichables !"
STRING_ERROR_WRONG_TYPE3				" Seulement les clés (Type 3) sont impartables !"
STRING_INITIALIZATION					"Initialisation"
STRING_ERROR_THREAD						"Erreur lors du lancement d'une thread : "
STRING_ERROR_MESSAGE_RECEIVE			"Erreur lors de la réception d'un message : "
STRING_NEW_MESSAGE_RECEIVED				"Nouveau message de "
STRING_ERROR_MESSAGE_RECEIVE2			"Ce message ne peut être reçu :"
STRING_ERROR_COULD_NOT_DELETE_ADDRESS	"Impossible de supprimer l'adresse"
STRING_ERROR_PERSON_ALREADY_EXISTS		"Cette personne est déjà enregistrée"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS "Une personne de ce nom est déjà enregistrée"
STRING_ERROR_SAVING_MESSAGE_FAILED		"Impossible de sauvegarder le message : "
STRING_ERROR_LOADING_SETTINGS_FAILED	"Impossible de charger la configuration : "
STRING_ERROR_OPEN_SETTINGS				"Impossible de lire la configuration : "
STRING_ERROR_SAVE_SETTINGS				"Impossible de sauvegarder la configuration : "
STRING_ERROR_NO_PERSON_WITH_NUMBER		"Impossible de trouver une personne avec le numéro : "
STRING_ERROR_DELETE_MESSAGE				"Impossible de supprimer le message"
STRING_ADDED_KEY_TO_PERSON				"Clé ajouté pour la personne avec le numéro : "
STRING_RETURN_PASSPHRASE				"Phrase secrète (à nouveau)"
STRING_FORM_NAME_MIN_2_CHARS			"Le nom doit faire au moins 2 caractères !"
STRING_FORM_NUMBER_MIN_7_CHARS			"Le numéro de téléphone doit faire au moins 7 charactères !"
STRING_FORM_PASS_MIN_5_CHARS			"La phrase secrète doit faire au moins 5 caractères !"
STRING_FORM_PASS_NOT_MATCH_REPEAT		"Les deux phrases entrées ne correspondent pas !"
STRING_FORM_PASS_NOT_MATCH				"Mauvaise phrase secrète!"
STRING_UNREAD_INBOX						"Nouveaux messages"
STRING_ERROR_DECRYPT					"Erreur lors de déchiffrement: "
STRING_INFO								"Info"
STRING_VERSION							"Version: "
STRING_BUILD							"Build: "
STRING_READ_INBOX						"Vieux messages"
STRING_REPLY							"Répondre"
STRING_NEW_MESSAGES_RECEIVED			"Nouveau message reçu"
