# portuguese language definition
ICON_KEY											"key.png"
ICON_NO_KEY											"nokey.png"
STRING_WELCOME										"Bemvindo!"
STRING_ENTER_PASSPHRASE								"Entre com a frase senha"
STRING_PASSPHRASE									"Senha:"
STRING_OK											"OK"
STRING_EXIT											"Sair"
STRING_ADDRESSBOOK									"Livro de Endereços"
STRING_DELETE_ADDRESS								"Excluir endereço"
STRING_KEY_LIST										"Chaves recebidos"
STRING_IMPORT_KEY_FROM_RECEIVED						"Importar chave da mensagem"
STRING_GENERATING_KEYPAIR							"Gerando o par de chaves pública/privada..."
STRING_BACK											"Voltar"
STRING_PUBLIC_KEYS									"Chaves públicas existindos"
STRING_DELETE_KEY									"Excluir chave"
STRING_NO_KEY_FOR_SENDER							"Chave não existindo"
STRING_SEND_MESSAGE									"Enviar mensagem"
STRING_ADDRESS_CHOICE								"Seleção de endereço"
STRING_SELECT_PLEASE								"Selecione endereço"
STRING_YOUR_NAME									"Seu nome"
STRING_YOUR_NUMBER									"Seu número de telefone"
STRING_NEW_ENTRY									"Novo registro"
STRING_EDIT_ENTRY									"Modificar registo"
STRING_NEW_MESSAGE									"Criar novo SMS"
STRING_NO_MESSAGEBOX								"Não tem mensagem"
STRING_SEND_PUBKEY									"Envie chave pública (sem codificação)"
STRING_NUMBER_WITH_SPACES							" Número: "
STRING_KEY_1										" Chave "
STRING_CANCEL										"Cancelar"
STRING_ERROR_ONLY_ENCRYPTED_SENDING					"Só é possível enviar um SMS as pessoas cujas chaves públicas existem!"
STRING_CHANGE_NAME									"Editar nome"
STRING_NAME											"Nome:"
STRING_NUMBER										"Número:"
STRING_MESSAGE										"Mensagem:"
STRING_NEW_SMS										"Novo SMS"
STRING_INBOX										"Entradas"
STRING_OUTBOX										"Mensagens enviadas"
STRING_CLEAR_MEMORY									"Eliminar memória"
STRING_MENU											"Menu"
STRING_TEXT											"Texto"
STRING_SENDING_MESSAGE								"Enviando mensagem "
STRING_VIEW_MESSAGE									"Mostrar mensagem"
STRING_IMPORT_KEY									"Importar chave pública"
STRING_DELETE_MESSAGE								"Excluir mensagem"
STRING_MESSAGE_TYPE									"Tipo:"
STRING_FORM_INCOMPLETE								"Campos incompletas!"
STRING_ENCRYPT_MESSAGE								"Codificando mensagem..."
STRING_DECRYPT_MESSAGE								"Decodificando mensagem..."
STRING_ERROR_WRONG_TYPE								" Só é possível mostrar mensagems (Tipo 1)!"
STRING_ERROR_WRONG_TYPE2							" Só é possível importar chaves (Tipo 3)!"
STRING_INITIALIZATION								"Initialização"
STRING_YOUR_NUMBER									"Seu número do telefone: "
STRING_ERROR_THREAD									"Erro detectado durante a initialização de Thread: "
STRING_ERROR_MESSAGE_RECEIVE						"Erro detectado durante o recebimento de mensagem: "
STRING_NEW_MESSAGE_RECEIVED							"Recebeu uma nova mensagem de "
STRING_ERROR_MESSAGE_RECEIVE2						"Não foi possível receber a mensagem: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS				"Não foi possível excluir o endereço"
STRING_ERROR_DELETE_MESSAGE							"Não foi possível excluir a mensagem"
STRING_ERROR_PERSON_ALREADY_EXISTS					"Pessoa já existe no Livro de Endereços"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS		"Pessoa com esse nome já existe no Livro de Endereços"
STRING_ERROR_SAVING_MESSAGE_FAILED					"Não foi possível salvar a mensagem: "
STRING_ERROR_LOADING_SETTINGS_FAILED				"Não foi possível carregar a Configuração: "
STRING_ERROR_OPEN_SETTINGS							"Não foi possível abrir a Configuração: "
STRING_ERROR_SAVE_SETTINGS							"Não foi possível salvar a Configuração: "
STRING_ERROR_NO_PERSON_WITH_NUMBER					"Pessoa com esse número não foi encontrado: "
STRING_ADDED_KEY_TO_PERSON							"Chave foi adicionado á pessoa com esse número: "
STRING_RETURN_PASSPHRASE							"Confirme senha"
STRING_FORM_NAME_MIN_2_CHARS						"O nome tem que ter no mínimo 2 letras!"
STRING_FORM_NUMBER_MIN_7_CHARS						"O número do telefone tem que ter no mínimo 7 caracteres!"
STRING_FORM_PASS_MIN_5_CHARS						"A senha tem que ter no mínimo 5 caracteres!"
STRING_FORM_PASS_NOT_MATCH_REPEAT					"A primeira e segunda senha não são idênticas!"
STRING_FORM_PASS_NOT_MATCH							"Senha errado!"
STRING_UNREAD_INBOX									"Novas mensagens recebidas"
STRING_READ_INBOX									"Entradas"
STRING_ERROR_DECRYPT								"Erro detectado durante decodificação: "
STRING_INFO											"Info"
STRING_VERSION										"Version: "
STRING_BUILD										"Build: "
STRING_REPLY										"Responder"
STRING_NEW_MESSAGES_RECEIVED						"Recebeu uma nova mensagem"
