# english language definition
ICON_KEY										"key.png"
ICON_NO_KEY										"nokey.png"
STRING_WELCOME									"Welcome!"
STRING_ENTER_PASSPHRASE							"Enter passphrase"
STRING_PASSPHRASE								"Password:"
STRING_OK										"OK"
STRING_EXIT										"EXIT"
STRING_ADDRESSBOOK								"Addressbook"
STRING_DELETE_ADDRESS 							"Delete Address"
STRING_KEY_LIST									"Received keys"
STRING_GENERATING_KEYPAIR						"Generating keypair..."
STRING_PUBLIC_KEYS								"Public keys on system"
STRING_BACK										"Back"
STRING_YOUR_NAME								"Your Name"
STRING_YOUR_NUMBER								"Your Phonenumber"
STRING_SMSC_GSM_NUMBER							"GCSS Phonenumber"
STRING_NEW_ENTRY								"New entry"
STRING_EDIT_ENTRY								"Edit entry"
STRING_NEW_MESSAGE								"Write message"
STRING_SEND_PUBKEY								"Send pubkey (not encrypted)"
STRING_NUMBER_WITH_SPACES						" number: "
STRING_KEY_1									" key "
STRING_CANCEL									"Cancel"
STRING_ERROR_ONLY_ENCRYPTED_SENDING				"You can only send an SMS if you have the recipient's public key!"
STRING_CHANGE_NAME								"Change name"
STRING_NAME										"Name:"
STRING_NUMBER									"Number:"
STRING_MESSAGE									"Message:"
STRING_NEW_SMS									"Write SMS"
STRING_INBOX									"Inbox"
STRING_OUTBOX									"Sent messages"
STRING_CLEAR_MEMORY								"Clear memory"
STRING_MENU										"Menu"
STRING_TEXT										"Text"
STRING_SENDING_MESSAGE							"Sending message "
STRING_VIEW_MESSAGE								"View message"
STRING_IMPORT_KEY								"Import key"
STRING_IMPORT_KEY_FROM_RECEIVED					"Import key from message"
STRING_DELETE_KEY								"Delete key"
STRING_NO_KEY_FOR_SENDER						"Missing key"
STRING_ADDRESS_CHOICE							"Select Address"
STRING_SEND_MESSAGE								"Send message"
STRING_NO_MESSAGEBOX							"No Messagebox"
STRING_SELECT_PLEASE							"Choose Address"
STRING_DELETE_MESSAGE							"Delete message"
STRING_MESSAGE_TYPE								"Type:"
STRING_FORM_INCOMPLETE							"invalid entry!"
STRING_ENCRYPT_MESSAGE							"encrypting message ..."
STRING_DECRYPT_MESSAGE							"decrypting message ..."
STRING_ERROR_WRONG_TYPE1						" Only text messages (Type 1) are displayable!"
STRING_ERROR_WRONG_TYPE3						" Only keys (Type 3) can be imported!"
STRING_INITIALIZATION							"Initialization"
STRING_YOUR_NUMBER								"Your telephone number:"
STRING_ERROR_THREAD								"Error while starting thread: "
STRING_ERROR_MESSAGE_RECEIVE					"Error while receiving message: "
STRING_NEW_MESSAGE_RECEIVED						"New message from "
STRING_ERROR_MESSAGE_RECEIVE2					"Message could not be received: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS			"Failed to delete address"
STRING_ERROR_PERSON_ALREADY_EXISTS				"Person already has an entry"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS	"A person by this name already exists"
STRING_ERROR_SAVING_MESSAGE_FAILED				"Failed to save message: "
STRING_ERROR_LOADING_SETTINGS_FAILED			"Failed to load settings: "
STRING_ERROR_OPEN_SETTINGS						"Failed to open settings: "
STRING_ERROR_SAVE_SETTINGS						"Failed to save settings: "
STRING_ERROR_NO_PERSON_WITH_NUMBER				"Failed to find person with number: "
STRING_ERROR_DELETE_MESSAGE						"Failed to delete message"
STRING_ADDED_KEY_TO_PERSON						"Key added to person with number: "
STRING_RETURN_PASSPHRASE						"Repeat passphrase"
STRING_FORM_NAME_MIN_2_CHARS					"Name must be at least 2 characters!"
STRING_FORM_NUMBER_MIN_7_CHARS					"Phonenumber must be at least 7 characters!"
STRING_FORM_PASS_MIN_5_CHARS					"Passphrase must be at least 5 characters!"
STRING_FORM_PASS_NOT_MATCH_REPEAT				"1. and 2. passphrase entry do not match!"
STRING_FORM_PASS_NOT_MATCH						"Wrong passphrase!"
STRING_READ_INBOX								"Old Messages"
STRING_UNREAD_INBOX								"New Messages"
STRING_ERROR_DECRYPT							"Error during decryption: "
STRING_INFO										"Info"
STRING_VERSION									"Version: "
STRING_BUILD									"Build: "
STRING_REPLY									"Reply"
STRING_NEW_MESSAGES_RECEIVED					"New Message received"
