/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * Local interface for ScheduleSession.
 * @generated 
 * @wtp generated
 */
public interface ScheduleSessionLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public ejbs.ScheduleItemData addScheduleItem( java.lang.String name,int startTime,int endTime,int day,java.lang.String scheduleID ) ;

   public java.util.List getScheduleItem( java.lang.String name ) ;

   public java.util.List getAllScheduleItems(  ) ;

   public java.util.List getScheduleItemesForScheduleID( java.lang.String scheduleID ) ;

}
