/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * Local home interface for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public interface ScheduleItemLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ScheduleItemLocal";
   public static final String JNDI_NAME="ScheduleItemLocal";

   public ejbs.ScheduleItemLocal create(java.lang.String name)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByScheduleId(java.lang.String scheduleId)
      throws javax.ejb.FinderException;

   public java.util.Collection findByName(java.lang.String name)
      throws javax.ejb.FinderException;

   public ejbs.ScheduleItemLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
