/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * Local home interface for ScheduleSession.
 * @generated 
 * @wtp generated
 */
public interface ScheduleSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ScheduleSessionLocal";
   public static final String JNDI_NAME="ScheduleSessionLocal";

   public ejbs.ScheduleSessionLocal create()
      throws javax.ejb.CreateException;

}
