/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * Local interface for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public interface ScheduleItemLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-user-doc --> CMP Field itemId Returns the itemId
    * @return the itemId <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getItemId(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the itemId
    * @param java.lang.Integer the new itemId value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setItemId( java.lang.Integer itemId ) ;

   /**
    * <!-- begin-user-doc --> CMP Field name Returns the name
    * @return the name <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String getName(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the name
    * @param java.lang.String the new name value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setName( java.lang.String name ) ;

   /**
    * <!-- begin-user-doc --> CMP Field startTime Returns the startTime
    * @return the startTime <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getStartTime(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the startTime
    * @param java.lang.Integer the new startTime value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setStartTime( java.lang.Integer startTime ) ;

   /**
    * <!-- begin-user-doc --> CMP Field endTime Returns the endTime
    * @return the endTime <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getEndTime(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the endTime
    * @param java.lang.Integer the new endTime value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setEndTime( java.lang.Integer endTime ) ;

   /**
    * <!-- begin-user-doc --> CMP Field day Returns the day
    * @return the day <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getDay(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the day
    * @param java.lang.Integer the new day value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setDay( java.lang.Integer day ) ;

   /**
    * <!-- begin-user-doc --> CMP Field scheduleId Returns the scheduleId
    * @return the scheduleId <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String getScheduleId(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the scheduleId
    * @param java.lang.String the new scheduleId value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setScheduleId( java.lang.String scheduleId ) ;

}
