/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * Data object for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public class ScheduleItemData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.Integer itemId;
   private java.lang.String name;
   private java.lang.Integer startTime;
   private java.lang.Integer endTime;
   private java.lang.Integer day;
   private java.lang.String scheduleId;

  /* begin value object */

  /* end value object */

   public ScheduleItemData()
   {
   }

   public ScheduleItemData( java.lang.Integer itemId,java.lang.String name,java.lang.Integer startTime,java.lang.Integer endTime,java.lang.Integer day,java.lang.String scheduleId )
   {
      setItemId(itemId);
      setName(name);
      setStartTime(startTime);
      setEndTime(endTime);
      setDay(day);
      setScheduleId(scheduleId);
   }

   public ScheduleItemData( ScheduleItemData otherData )
   {
      setItemId(otherData.getItemId());
      setName(otherData.getName());
      setStartTime(otherData.getStartTime());
      setEndTime(otherData.getEndTime());
      setDay(otherData.getDay());
      setScheduleId(otherData.getScheduleId());

   }

   public java.lang.Integer getPrimaryKey() {
     return  getItemId();
   }

   public java.lang.Integer getItemId()
   {
      return this.itemId;
   }
   public void setItemId( java.lang.Integer itemId )
   {
      this.itemId = itemId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }
   public void setName( java.lang.String name )
   {
      this.name = name;
   }

   public java.lang.Integer getStartTime()
   {
      return this.startTime;
   }
   public void setStartTime( java.lang.Integer startTime )
   {
      this.startTime = startTime;
   }

   public java.lang.Integer getEndTime()
   {
      return this.endTime;
   }
   public void setEndTime( java.lang.Integer endTime )
   {
      this.endTime = endTime;
   }

   public java.lang.Integer getDay()
   {
      return this.day;
   }
   public void setDay( java.lang.Integer day )
   {
      this.day = day;
   }

   public java.lang.String getScheduleId()
   {
      return this.scheduleId;
   }
   public void setScheduleId( java.lang.String scheduleId )
   {
      this.scheduleId = scheduleId;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("itemId=" + getItemId() + " " + "name=" + getName() + " " + "startTime=" + getStartTime() + " " + "endTime=" + getEndTime() + " " + "day=" + getDay() + " " + "scheduleId=" + getScheduleId());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof ScheduleItemData )
      {
         ScheduleItemData lTest = (ScheduleItemData) pOther;
         boolean lEquals = true;

         if( this.itemId == null )
         {
            lEquals = lEquals && ( lTest.itemId == null );
         }
         else
         {
            lEquals = lEquals && this.itemId.equals( lTest.itemId );
         }
         if( this.name == null )
         {
            lEquals = lEquals && ( lTest.name == null );
         }
         else
         {
            lEquals = lEquals && this.name.equals( lTest.name );
         }
         if( this.startTime == null )
         {
            lEquals = lEquals && ( lTest.startTime == null );
         }
         else
         {
            lEquals = lEquals && this.startTime.equals( lTest.startTime );
         }
         if( this.endTime == null )
         {
            lEquals = lEquals && ( lTest.endTime == null );
         }
         else
         {
            lEquals = lEquals && this.endTime.equals( lTest.endTime );
         }
         if( this.day == null )
         {
            lEquals = lEquals && ( lTest.day == null );
         }
         else
         {
            lEquals = lEquals && this.day.equals( lTest.day );
         }
         if( this.scheduleId == null )
         {
            lEquals = lEquals && ( lTest.scheduleId == null );
         }
         else
         {
            lEquals = lEquals && this.scheduleId.equals( lTest.scheduleId );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.itemId != null) ? this.itemId.hashCode() : 0);

      result = 37*result + ((this.name != null) ? this.name.hashCode() : 0);

      result = 37*result + ((this.startTime != null) ? this.startTime.hashCode() : 0);

      result = 37*result + ((this.endTime != null) ? this.endTime.hashCode() : 0);

      result = 37*result + ((this.day != null) ? this.day.hashCode() : 0);

      result = 37*result + ((this.scheduleId != null) ? this.scheduleId.hashCode() : 0);

      return result;
   }

}
