# italian language definition
ICON_KEY									"key.png"
ICON_NO_KEY									"nokey.png"
STRING_WELCOME								"benvenuto/a!"
STRING_ENTER_PASSPHRASE						"inserire passphrase"
STRING_PASSPHRASE							"passphrase:"
STRING_OK									"OK"
STRING_EXIT									"esci"
STRING_ADDRESSBOOK							"rubbrica indirizzi"
STRING_DELETE_ADDRESS						"eliminare indirizzo"
STRING_KEY_LIST								"chiavi ricevute"
STRING_IMPORT_KEY_FROM_RECEIVED				"importare chiave dal messaggio"
STRING_GENERATING_KEYPAIR					"generare coppia di chiavi ..."
STRING_BACK									"indietro"
STRING_PUBLIC_KEYS							"chiavi pubbliche"
STRING_DELETE_KEY							"cancellare chiave"
STRING_NO_KEY_FOR_SENDER					"niente chiave per mittente"
STRING_SEND_MESSAGE							"inviare messaggio"
STRING_ADDRESS_CHOICE						"scelta di indirizzo"
STRING_SELECT_PLEASE						"selezionare indirizzo"
STRING_YOUR_NAME							"il tuo nome"
STRING_YOUR_NUMBER							"il tuo numero di telefono"
STRING_NEW_ENTRY							"nuovo inserimento"
STRING_EDIT_ENTRY							"modificare inserimento"
STRING_NEW_MESSAGE							"scrivere messaggio"
STRING_NO_MESSAGEBOX						"nessun messaggio"
STRING_SEND_PUBKEY							"inviare chiave (decifrata)"
STRING_NUMBER_WITH_SPACES					" numero: "
STRING_KEY_1								" chiave "
STRING_CANCEL								"annullare"
STRING_ERROR_ONLY_ENCRYPTED_SENDING			"possono essere inviati messaggi solo a persone la cui chiave è presente!"
STRING_CHANGE_NAME							"cambiare nome"
STRING_NAME									"nome:"
STRING_NUMBER								"numero:"
STRING_MESSAGE								"messaggio:"
STRING_NEW_SMS								"creare nuovo messaggio"
STRING_INBOX								"messaggi in arrivo"
STRING_OUTBOX								"messaggi in inviati"
STRING_CLEAR_MEMORY							"cancella memoria"
STRING_MENU									"menu"
STRING_TEXT									"testo"
STRING_SENDING_MESSAGE						"inviare messaggio "
STRING_VIEW_MESSAGE							"vedere messaggio"
STRING_IMPORT_KEY							"importare chiave"
STRING_DELETE_MESSAGE						"eliminare messaggio"
STRING_MESSAGE_TYPE							"tipo di messaggio:"
STRING_FORM_INCOMPLETE						"campi incompleti!"
STRING_ENCRYPT_MESSAGE						"cifrare messaggio..."
STRING_DECRYPT_MESSAGE						"decifrare messaggio..."
STRING_ERROR_WRONG_TYPE						" errore: solo messaggi di testo (tipo 1)possono essere mostrati!"
STRING_ERROR_WRONG_TYPE2					" errore: solo chiavi (tipo 3) possono essere importate!"
STRING_INITIALIZATION						"inizializzazione"
STRING_YOUR_NUMBER							"il tuo numero di telefono:"
STRING_ERROR_THREAD							"errore nell'avviare Thread: "
STRING_ERROR_MESSAGE_RECEIVE				"errore nel ricevere messaggio: "
STRING_NEW_MESSAGE_RECEIVED					"nuovo messaggio ricevuto da "
STRING_ERROR_MESSAGE_RECEIVE2				"errore nel ricevere messaggio: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS		"errore nell' eliminare indirizzo"
STRING_ERROR_DELETE_MESSAGE					"errore nell' eliminare messaggio"
STRING_ERROR_PERSON_ALREADY_EXISTS			"persona già esistente nella rubbrica"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS	"persona con questo nome già esistente"
STRING_ERROR_SAVING_MESSAGE_FAILED			"errore nel salvare messaggio: "
STRING_ERROR_LOADING_SETTINGS_FAILED		"errore nel caricare settings: "
STRING_ERROR_OPEN_SETTINGS					"errore nell' aprire settings: "
STRING_ERROR_SAVE_SETTINGS					"errore nel salvare settings: "
STRING_ERROR_NO_PERSON_WITH_NUMBER			"errore nel trovare persona con questo numero: "
STRING_ADDED_KEY_TO_PERSON					"chiave aggiunta alla persona con questo numero: "
STRING_RETURN_PASSPHRASE					"confermare passphrase"
STRING_FORM_NAME_MIN_2_CHARS				"Il nome deve comprendere al minimo 2 caratteri!"
STRING_FORM_NUMBER_MIN_7_CHARS				"Il numero di telefono deve comprendere al minimo 7 ciffre!"
STRING_FORM_PASS_MIN_5_CHARS				"La passphrase deve comprendere al minimo 5 caratteri!"
STRING_FORM_PASS_NOT_MATCH_REPEAT			"1o e 2o inserimento della passphrase non identichi!"
STRING_FORM_PASS_NOT_MATCH					"Passphrase errata!"
STRING_READ_INBOX							"messaggi vecchi"
STRING_UNREAD_INBOX							"messaggi non letti"
STRING_ERROR_DECRYPT						"errore nel decifrare: "
STRING_INFO									"info"
STRING_VERSION								"Version: "
STRING_BUILD								"Build: "
STRING_REPLY								"rispondere"
STRING_NEW_MESSAGES_RECEIVED				"nuovo messaggio ricevuto"
