/*
 * Generated by XDoclet - Do not edit!
 */
package test.tusc;

/**
 * Local home interface for MySession.
 * @generated 
 * @wtp generated
 */
public interface MySessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MySessionLocal";
   public static final String JNDI_NAME="MySessionLocal";

   public test.tusc.MySessionLocal create()
      throws javax.ejb.CreateException;

}
