/*
 * Generated by XDoclet - Do not edit!
 */
package test.tusc;

/**
 * Local interface for MySession.
 * @generated 
 * @wtp generated
 */
public interface MySessionLocal
   extends javax.ejb.EJBLocalObject
{

}
