/*
 * Generated by XDoclet - Do not edit!
 */
package test.tusc;

/**
 * Remote interface for MySession.
 * @generated 
 * @wtp generated
 */
public interface MySession
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String learnJ2EE( java.lang.String param )
      throws java.rmi.RemoteException;

}
