# german language definition
ICON_KEY						"key.png"
ICON_NO_KEY						"nokey.png"
STRING_WELCOME					"Willkommen!"
STRING_ENTER_PASSPHRASE			"Passwort eingeben"
STRING_PASSPHRASE				"Passwort:"
STRING_OK						"OK"
STRING_EXIT						"Verlassen"
STRING_ADDRESSBOOK				"Adressbuch"
STRING_DELETE_ADDRESS			"Adresse löschen"
STRING_KEY_LIST					"empfangene Schlüssel"
STRING_IMPORT_KEY_FROM_RECEIVED	"Schlüssel aus Nachricht importieren"
STRING_GENERATING_KEYPAIR		"Erzeuge Schlüsselpaar..."
STRING_BACK						"Zurück"
STRING_PUBLIC_KEYS				"Vorhandene Schlüssel"
STRING_DELETE_KEY				"Schlüssel löschen"
STRING_NO_KEY_FOR_SENDER		"Kein Schlüssel vorhanden"
STRING_SEND_MESSAGE				"Nachricht senden"
STRING_ADDRESS_CHOICE			"Adressauswahl"
STRING_SELECT_PLEASE			"Adresse auswählen"
STRING_YOUR_NAME				"Dein Name"
STRING_YOUR_NUMBER				"Deine Telefonnummer"
STRING_NEW_ENTRY				"Neuer Eintrag"
STRING_EDIT_ENTRY				"Eintrag bearbeiten"
STRING_NEW_MESSAGE				"Nachricht verfassen"
STRING_NO_MESSAGEBOX			"Keine Nachricht"
STRING_SEND_PUBKEY				"Schlüssel senden (unverschlüsselt)"
STRING_NUMBER_WITH_SPACES		" Nummer: "
STRING_KEY_1					" Schlüssel "
STRING_CANCEL					"Abbruch"
STRING_ERROR_ONLY_ENCRYPTED_SENDING	"Es können SMS nur an Personen geschickt werden, deren Schlüssel vorhanden ist!"
STRING_CHANGE_NAME				"Name ändern"
STRING_NAME						"Name:"
STRING_NUMBER					"Nummer:"
STRING_MESSAGE					"Nachricht:"
STRING_NEW_SMS					"Neue SMS verfassen"
STRING_INBOX					"Eingang"
STRING_OUTBOX					"Gesendet"
STRING_CLEAR_MEMORY				"Speicher löschen"
STRING_MENU						"Menü"
STRING_TEXT						"Text"
STRING_SENDING_MESSAGE			"Sende Nachricht "
STRING_VIEW_MESSAGE				"Nachricht ansehen"
STRING_IMPORT_KEY				"Schlüssel importieren"
STRING_DELETE_MESSAGE			"Nachricht löschen"
STRING_MESSAGE_TYPE				"Typ:"
STRING_FORM_INCOMPLETE			"unvollständige Felder!"
STRING_ENCRYPT_MESSAGE			"verschlüssele Nachricht..."
STRING_DECRYPT_MESSAGE			"entschlüssele Nachricht..."
STRING_ERROR_WRONG_TYPE			" Nur Textnachrichten (Typ 1)können angezeigt werden!"
STRING_ERROR_WRONG_TYPE2		" Nur Schlüssel (Typ 3) können importiert werden!"
STRING_INITIALIZATION			"Initialisierung"
STRING_YOUR_NUMBER				"Deine Telefonnummer:"
STRING_ERROR_THREAD				"Fehler beim Starten von Thread: "
STRING_ERROR_MESSAGE_RECEIVE	"Fehler beim Empfang von Nachricht: "
STRING_NEW_MESSAGE_RECEIVED		"Neue Nachricht von "
STRING_ERROR_MESSAGE_RECEIVE2	"Nachricht konnte nicht empfangen werden: "
STRING_ERROR_COULD_NOT_DELETE_ADDRESS	"Löschen der Adresse fehlgeschlagen"
STRING_ERROR_DELETE_MESSAGE		"Löschen der Nachricht fehlgeschlagen"
STRING_ERROR_PERSON_ALREADY_EXISTS	"Person gibt es bereits im Adressbuch"
STRING_ERROR_PERSON_WITH_NAME_ALREADY_EXISTS "Person mit diesem Namen ist bereits angelegt"
STRING_ERROR_SAVING_MESSAGE_FAILED	"Konnte Nachricht nicht speichern: "
STRING_ERROR_LOADING_SETTINGS_FAILED	"Laden der Settings fehlgeschlagen: "
STRING_ERROR_OPEN_SETTINGS		"Öffnen der Settings fehlgeschlagen: "
STRING_ERROR_SAVE_SETTINGS		"Speichern der Settings fehlgeschlagen: "
STRING_ERROR_NO_PERSON_WITH_NUMBER	"Keine Person mit dieser Nummer gefunden: "
STRING_ADDED_KEY_TO_PERSON		"Schlüssel wurde der Person mit dieser Nummer hinzugefügt: "
STRING_RETURN_PASSPHRASE		"Passwort bestätigen"
STRING_FORM_NAME_MIN_2_CHARS	"Der Name muss mind. 2 Zeichen lang sein!"
STRING_FORM_NUMBER_MIN_7_CHARS	"Die Telefonnummer muss mind. 7 Ziffern lang sein!"
STRING_FORM_PASS_MIN_5_CHARS	"Das Passwort muss mind. 5 Zeichen lang sein!"
STRING_FORM_PASS_NOT_MATCH_REPEAT	"1. und 2. Passworteingabe nicht identisch!"
STRING_FORM_PASS_NOT_MATCH		"Falsches Passwort!"
STRING_READ_INBOX				"Alte Nachrichten"
STRING_UNREAD_INBOX				"Neue Nachrichten"
STRING_ERROR_DECRYPT			"Fehler beim Entschlüsseln: "
STRING_INFO						"Info"
STRING_VERSION					"Version: "
STRING_BUILD					"Build: "
STRING_REPLY					"Antworten"
STRING_NEW_MESSAGES_RECEIVED	"Neue Nachricht empfangen"
