/*
 * Generated by XDoclet - Do not edit!
 */
package demo;

/**
 * Home interface for Hello.
 * @generated 
 * @wtp generated
 */
public interface HelloHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Hello";
   public static final String JNDI_NAME="Hello";

   public demo.Hello create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
