/*
 * Generated by XDoclet - Do not edit!
 */
package demo;

/**
 * Local home interface for Hello.
 * @generated 
 * @wtp generated
 */
public interface HelloLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HelloLocal";
   public static final String JNDI_NAME="HelloLocal";

   public demo.HelloLocal create()
      throws javax.ejb.CreateException;

}
