/*
 * Generated by XDoclet - Do not edit!
 */
package demo;

/**
 * Remote interface for Hello.
 * @generated 
 * @wtp generated
 */
public interface Hello
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String hello(  )
      throws java.rmi.RemoteException;

}
