/*
 * Generated by XDoclet - Do not edit!
 */
package demo;

/**
 * Local interface for Hello.
 * @generated 
 * @wtp generated
 */
public interface HelloLocal
   extends javax.ejb.EJBLocalObject
{

}
