/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * Remote interface for ScheduleSession.
 * @generated 
 * @wtp generated
 */
public interface ScheduleSession
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public ejbs.ScheduleItemData addScheduleItem( java.lang.String name,int startTime,int endTime,int day,java.lang.String scheduleID )
      throws java.rmi.RemoteException;

   public java.util.List getScheduleItem( java.lang.String name )
      throws java.rmi.RemoteException;

   public java.util.List getAllScheduleItems(  )
      throws java.rmi.RemoteException;

   public java.util.List getScheduleItemesForScheduleID( java.lang.String scheduleID )
      throws java.rmi.RemoteException;

}
