/*
 * Generated by XDoclet - Do not edit!
 */
package ejbs;

/**
 * CMP layer for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public abstract class ScheduleItemCMP
   extends ejbs.ScheduleItemBean
   implements javax.ejb.EntityBean
{

   public ejbs.ScheduleItemData getData()
   {
      ejbs.ScheduleItemData dataHolder = null;
      try
      {
         dataHolder = new ejbs.ScheduleItemData();

         dataHolder.setItemId( getItemId() );
         dataHolder.setName( getName() );
         dataHolder.setStartTime( getStartTime() );
         dataHolder.setEndTime( getEndTime() );
         dataHolder.setDay( getDay() );
         dataHolder.setScheduleId( getScheduleId() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(java.lang.String name)
    */
   public void ejbPostCreate(java.lang.String name)
   {
   }

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

/* Value Objects END */

   public abstract java.lang.Integer getItemId() ;

   public abstract void setItemId( java.lang.Integer itemId ) ;

   public abstract java.lang.String getName() ;

   public abstract void setName( java.lang.String name ) ;

   public abstract java.lang.Integer getStartTime() ;

   public abstract void setStartTime( java.lang.Integer startTime ) ;

   public abstract java.lang.Integer getEndTime() ;

   public abstract void setEndTime( java.lang.Integer endTime ) ;

   public abstract java.lang.Integer getDay() ;

   public abstract void setDay( java.lang.Integer day ) ;

   public abstract java.lang.String getScheduleId() ;

   public abstract void setScheduleId( java.lang.String scheduleId ) ;

}
