/* ** *** ***** ******* *********** *************
 * DIA - Dipartimento di Informatica ed Applicazioni "Renato M. Capocelli" 				
 * http://www.dia.unisa.it			
 * 
 ************* *********** ******* ***** *** ** */

package crymes.server.gui;

import javax.swing.JOptionPane;

import crymes.server.CSettings;
import crymes.server.gui.MainFrame;
import crymes.server.gui.PassphraseDialog;



/**
 *
 * @author  maucem
 */
@SuppressWarnings("serial")
public class PassphraseDialog extends javax.swing.JDialog implements java.awt.event.ActionListener {
    
	private MainFrame _mf;
	private static int tentative=0;
	private static PassphraseDialog  _passphraseDialog = null;
	
    /** Creates new form passphraseDialog */
    private PassphraseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        _mf = (MainFrame) parent;
        initComponents();
        
    }
    
    public static PassphraseDialog getInstance(java.awt.Frame parent){
    	
    	if (_passphraseDialog==null)
    		_passphraseDialog = new PassphraseDialog(parent, false);
    	else {
    	 if (++tentative == CSettings.getMaxTentativePassphrase()+1){
          	JOptionPane.showMessageDialog(null, "Incorrect passphrase", "Error", JOptionPane.ERROR_MESSAGE);
          	System.exit(-1);
          } else {
         	 tentativi.setText("#"+(tentative)+" of "+CSettings.getMaxTentativePassphrase());
         	 _passphraseDialog.repaint();
          }
    	}
    	return _passphraseDialog;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tentativi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Passphrase");
        setModal(true);
       

        jButton1.setText("OK");
        jButton1.addActionListener(this);

        jPasswordField1.addActionListener(this);

        jLabel1.setText("Insert the Passphrase");

        jButton2.setText("Exit");
        jButton2.addActionListener(this);
        
        tentativi.setText("#"+tentative+" of "+CSettings.getMaxTentativePassphrase());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tentativi))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPasswordField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(tentativi))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {    	
        if (evt.getSource() == jPasswordField1) {
            PassphraseDialog.this.doProcess(evt);
        }
        else if (evt.getSource() == jButton1) {
            PassphraseDialog.this.doProcess(evt);
        }  else if (evt.getSource() == jButton2) {
            PassphraseDialog.this.exitAction(evt);
        }
    }

    
   
    

   

    private void exitAction(java.awt.event.ActionEvent evt) {
    	System.exit(-1);
    }
    
    private void doProcess(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doProcess
    	char [] chars = jPasswordField1.getPassword();
    	StringBuffer sb = new StringBuffer();
    	sb.append(chars);    	
    	jPasswordField1.setText("");
    	jPasswordField1.setFocusable(true);
    	_mf.passphraseDialogCallback(sb.toString());
    }//GEN-LAST:eve
    
  
	protected void callbackPassphrase (boolean valid) {
		if (valid) tentative = 0;
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private static javax.swing.JLabel tentativi;
    // End of variables declaration//GEN-END:variables
    
}
