package smsserver.gui;

import java.awt.Dimension;
/*
 * connectionStatusPanel.java
 *
 * Created on 22 settembre 2007, 18.13
 */

/**
 *
 * @author  maucem
 */
@SuppressWarnings("serial")
public class ConnectionStatusPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form connectionStatusPanel
     */
    public ConnectionStatusPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signalBarGSM = new javax.swing.JProgressBar();
        signalBarGSM.setVisible(false);
        labelStatusEmulator = new javax.swing.JLabel();
        labelStatusGSM = new javax.swing.JLabel();
        labelNumberGSM = new javax.swing.JLabel();
        labelNumberGSM.setVisible(false);
        labelNumberEmulator = new javax.swing.JLabel();
        labelNumberEmulator.setVisible(false);
        
        setPreferredSize(new Dimension(700,50));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Emulator:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("GSM Modem:");

        
        signalBarGSM.setStringPainted(true);

        labelStatusEmulator.setText("not connected.");

        labelStatusGSM.setText("not connected.");

        labelNumberGSM.setText("+393332211212");

        labelNumberEmulator.setText("jLabel6");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2))
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelStatusEmulator)
                    .add(labelStatusGSM))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(labelNumberGSM)
                        .add(16, 16, 16)
                        .add(signalBarGSM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(labelNumberEmulator))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(labelStatusEmulator)
                        .add(labelNumberEmulator)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(signalBarGSM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelNumberGSM)
                            .add(labelStatusGSM)
                            .add(jLabel2))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents
    
    public void setStatusEmulator(boolean connected, String number){
    	if (connected)
    		labelStatusEmulator.setText("connected.");
    	else
    		labelStatusEmulator.setText("not connected.");
    	labelNumberEmulator.setVisible(connected);
    	if (number!=null)
    		labelNumberEmulator.setText(number);
    }
    
    public void setStatusGSMModem(boolean connected, String number){
    	if (connected)
    		labelStatusGSM.setText("connected.");
    	else
    		labelStatusGSM.setText("not connected.");
    	labelNumberGSM.setVisible(connected);
    	signalBarGSM.setVisible(connected);
    	if (number!=null){
    		labelNumberGSM.setText(number);
    	}
    }
    public void setSignalGSMModem(int value){
    	signalBarGSM.setValue(value);
    	signalBarGSM.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNumberEmulator;
    private javax.swing.JLabel labelNumberGSM;
    private javax.swing.JLabel labelStatusEmulator;
    private javax.swing.JLabel labelStatusGSM;
    private javax.swing.JProgressBar signalBarGSM;
    // End of variables declaration//GEN-END:variables
    
}
