/*
 * logPanel.java
 *
 * Created on 26 settembre 2007, 10.17
 */

package smsserver.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

/**
 *
 * @author  maucem
 */
public class logPanel extends javax.swing.JPanel implements java.awt.event.ActionListener {
    
    /**
     * Creates new form logPanel
     */
	private MainFrame _parent;
    public logPanel(MainFrame parent) {
    	_parent = parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        messageLogArea = new javax.swing.JTextArea();
        
        exitButton = new javax.swing.JButton();

        messageLogArea.setColumns(20);
        messageLogArea.setRows(5);
        
        messageLogArea.setLineWrap(true);
        messageLogArea.setDisabledTextColor(new Color(0,0,0));
        messageLogArea.setAutoscrolls(true);
        jScrollPane1.setAutoscrolls(true);
        messageLogArea.setEnabled(false);
        
        
        jScrollPane1.setViewportView(messageLogArea);
        
        
        exitButton.setText("Exit");
        exitButton.addActionListener(this);
        
        this.setPreferredSize(new Dimension(700,180));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(exitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(exitButton)
                )
        );
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == exitButton) {
           logPanel.this.doExit(evt);
        }
    }//GEN-END:initComponents

    private void doExit(java.awt.event.ActionEvent evt) {
    	int b = JOptionPane.showConfirmDialog(_parent, "Are you sure?", "SMS Server", JOptionPane.OK_CANCEL_OPTION);
    	
    	if ( b == JOptionPane.CANCEL_OPTION ){
    		return;
    	} else if ( b == JOptionPane.OK_OPTION ){
    		System.exit(0);
    	}
    }
    
    // Aggiunge un messaggio nella finestra dei log
    public void addMessageLog(String s){
    	
    	SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
    	String timestamp = sdf.format(new Date());
    	
    	String str = "";    	
    	if (messageLogArea.getText().length() > 0) 
    		str = messageLogArea.getText() + "\n";
    	str = timestamp + " - " + s + "\n";
    		messageLogArea.append(str);
    		
    	messageLogArea.setCaretPosition(messageLogArea.getText().length());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageLogArea;
    // End of variables declaration//GEN-END:variables
    
}
