/* soapWebApiSoapBindingProxy.h
   Generated by gSOAP 2.8.2 from WebApi.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapWebApiSoapBindingProxy_H
#define soapWebApiSoapBindingProxy_H
#include "soapH.h"
class WebApiSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'WebApiSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	WebApiSoapBinding()
	// { soap = soap_new(); endpoint = "http://www.legalcyclecl.infocert.it/wfca/services/WebApi"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
	{ soap = soap_new(); endpoint = "http://localhost:8081/wfca/services/WebApi"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://webapi.wfca.infocert.it", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~WebApiSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getToken' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getToken(_ns1__getToken *ns1__getToken, _ns1__getTokenResponse *ns1__getTokenResponse) { return soap ? soap_call___ns1__getToken(soap, endpoint, NULL, ns1__getToken, ns1__getTokenResponse) : SOAP_EOM; };
	/// Invoke 'login' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__login(_ns1__login *ns1__login, _ns1__loginResponse *ns1__loginResponse) { return soap ? soap_call___ns1__login(soap, endpoint, NULL, ns1__login, ns1__loginResponse) : SOAP_EOM; };
	/// Invoke 'attivaProcedimento' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__attivaProcedimento(_ns1__attivaProcedimento *ns1__attivaProcedimento, _ns1__attivaProcedimentoResponse *ns1__attivaProcedimentoResponse) { return soap ? soap_call___ns1__attivaProcedimento(soap, endpoint, NULL, ns1__attivaProcedimento, ns1__attivaProcedimentoResponse) : SOAP_EOM; };
	/// Invoke 'attivaProcedimentoWide' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__attivaProcedimentoWide(_ns1__attivaProcedimentoWide *ns1__attivaProcedimentoWide, _ns1__attivaProcedimentoWideResponse *ns1__attivaProcedimentoWideResponse) { return soap ? soap_call___ns1__attivaProcedimentoWide(soap, endpoint, NULL, ns1__attivaProcedimentoWide, ns1__attivaProcedimentoWideResponse) : SOAP_EOM; };
	/// Invoke 'aggiungiDocumentoAlProcedimento' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__aggiungiDocumentoAlProcedimento(_ns1__aggiungiDocumentoAlProcedimento *ns1__aggiungiDocumentoAlProcedimento, _ns1__aggiungiDocumentoAlProcedimentoResponse *ns1__aggiungiDocumentoAlProcedimentoResponse) { return soap ? soap_call___ns1__aggiungiDocumentoAlProcedimento(soap, endpoint, NULL, ns1__aggiungiDocumentoAlProcedimento, ns1__aggiungiDocumentoAlProcedimentoResponse) : SOAP_EOM; };
	/// Invoke 'getProcedimento' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getProcedimento(_ns1__getProcedimento *ns1__getProcedimento, _ns1__getProcedimentoResponse *ns1__getProcedimentoResponse) { return soap ? soap_call___ns1__getProcedimento(soap, endpoint, NULL, ns1__getProcedimento, ns1__getProcedimentoResponse) : SOAP_EOM; };
	/// Invoke 'avanzaProcedimento' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__avanzaProcedimento(_ns1__avanzaProcedimento *ns1__avanzaProcedimento, _ns1__avanzaProcedimentoResponse *ns1__avanzaProcedimentoResponse) { return soap ? soap_call___ns1__avanzaProcedimento(soap, endpoint, NULL, ns1__avanzaProcedimento, ns1__avanzaProcedimentoResponse) : SOAP_EOM; };
	/// Invoke 'getFlussi' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getFlussi(_ns1__getFlussi *ns1__getFlussi, _ns1__getFlussiResponse *ns1__getFlussiResponse) { return soap ? soap_call___ns1__getFlussi(soap, endpoint, NULL, ns1__getFlussi, ns1__getFlussiResponse) : SOAP_EOM; };
	/// Invoke 'getGiustificativi' of service 'WebApiSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getGiustificativi(_ns1__getGiustificativi *ns1__getGiustificativi, _ns1__getGiustificativiResponse *ns1__getGiustificativiResponse) { return soap ? soap_call___ns1__getGiustificativi(soap, endpoint, NULL, ns1__getGiustificativi, ns1__getGiustificativiResponse) : SOAP_EOM; };
};
#endif
