// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* WebApi.h
   Generated by wsdl2h 2.8.2 from ../../wsdl/WebApi.wsdl and typemap.dat
   2011-04-26 11:09:34 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on WebApi.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://webapi.wfca.infocert.it                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://webapi.wfca.infocert.it"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://webapi.wfca.infocert.it"
//gsoap ns1   schema namespace:	http://webapi.wfca.infocert.it
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class ns1__EccezioneAutenticazione.
class ns1__EccezioneAutenticazione;

//  Forward declaration of class ns1__EccezioneSistema.
class ns1__EccezioneSistema;

//  Forward declaration of class ns1__MetaDato.
class ns1__MetaDato;

//  Forward declaration of class ns1__Nota.
class ns1__Nota;

//  Forward declaration of class ns1__ArrayOfNota.
class ns1__ArrayOfNota;

//  Forward declaration of class ns1__Stato.
class ns1__Stato;

//  Forward declaration of class ns1__Step.
class ns1__Step;

//  Forward declaration of class ns1__ArrayOfStep.
class ns1__ArrayOfStep;

//  Forward declaration of class ns1__ArrayOf_USCORExsd_USCOREstring.
class ns1__ArrayOf_USCORExsd_USCOREstring;

//  Forward declaration of class ns1__Esito.
class ns1__Esito;

//  Forward declaration of class ns1__Attributo.
class ns1__Attributo;

//  Forward declaration of class ns1__ArrayOfAttributo.
class ns1__ArrayOfAttributo;

//  Forward declaration of class ns1__Funzione.
class ns1__Funzione;

//  Forward declaration of class ns1__ArrayOfFunzione.
class ns1__ArrayOfFunzione;

//  Forward declaration of class ns1__StepCompetenza.
class ns1__StepCompetenza;

//  Forward declaration of class ns1__ArrayOfStepCompetenza.
class ns1__ArrayOfStepCompetenza;

//  Forward declaration of class ns1__Procedimento.
class ns1__Procedimento;

//  Forward declaration of class ns1__Flusso.
class ns1__Flusso;

//  Forward declaration of class ns1__Giustificativo.
class ns1__Giustificativo;

//  Forward declaration of class _ns1__getToken.
class _ns1__getToken;

//  Forward declaration of class _ns1__getTokenResponse.
class _ns1__getTokenResponse;

//  Forward declaration of class _ns1__login.
class _ns1__login;

//  Forward declaration of class _ns1__loginResponse.
class _ns1__loginResponse;

//  Forward declaration of class _ns1__attivaProcedimento.
class _ns1__attivaProcedimento;

//  Forward declaration of class _ns1__attivaProcedimentoResponse.
class _ns1__attivaProcedimentoResponse;

//  Forward declaration of class _ns1__attivaProcedimentoWide.
class _ns1__attivaProcedimentoWide;

//  Forward declaration of class _ns1__attivaProcedimentoWideResponse.
class _ns1__attivaProcedimentoWideResponse;

//  Forward declaration of class _ns1__aggiungiDocumentoAlProcedimento.
class _ns1__aggiungiDocumentoAlProcedimento;

//  Forward declaration of class _ns1__aggiungiDocumentoAlProcedimentoResponse.
class _ns1__aggiungiDocumentoAlProcedimentoResponse;

//  Forward declaration of class _ns1__getProcedimento.
class _ns1__getProcedimento;

//  Forward declaration of class _ns1__getProcedimentoResponse.
class _ns1__getProcedimentoResponse;

//  Forward declaration of class _ns1__avanzaProcedimento.
class _ns1__avanzaProcedimento;

//  Forward declaration of class _ns1__avanzaProcedimentoResponse.
class _ns1__avanzaProcedimentoResponse;

//  Forward declaration of class _ns1__getFlussi.
class _ns1__getFlussi;

//  Forward declaration of class _ns1__getFlussiResponse.
class _ns1__getFlussiResponse;

//  Forward declaration of class _ns1__getGiustificativi.
class _ns1__getGiustificativi;

//  Forward declaration of class _ns1__getGiustificativiResponse.
class _ns1__getGiustificativiResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://webapi.wfca.infocert.it                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://webapi.wfca.infocert.it                                           *
 *                                                                            *
\******************************************************************************/


/// "http://webapi.wfca.infocert.it":EccezioneAutenticazione is a complexType.
class ns1__EccezioneAutenticazione
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":EccezioneSistema is a complexType.
class ns1__EccezioneSistema
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":MetaDato is a complexType.
class ns1__MetaDato
{ public:
/// Element nome of type xs:string.
    char*                                nome                          ;	///< Nullable pointer.
/// Element tipo of type xs:int.
    int                                  tipo                           1;	///< Required element.
/// Element valore of type xs:string.
    char*                                valore                        ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Nota is a complexType.
class ns1__Nota
{ public:
/// Element attivita of type xs:string.
    char*                                attivita                      ;	///< Nullable pointer.
/// Element dataOra of type xs:dateTime.
    time_t*                              dataOra                       ;	///< Nullable pointer.
/// Element descrizioneUtente of type xs:string.
    char*                                descrizioneUtente             ;	///< Nullable pointer.
/// Element testo of type xs:string.
    char*                                testo                         ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":ArrayOfNota is a complexType.
class ns1__ArrayOfNota
{ public:
/// Size of array of ns1__Nota* is 0..unbounded
   $int                                  __sizeitem                     0;
/// Pointer to array ns1__Nota* of length 0..unbounded
    ns1__Nota*                          *item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Stato is a complexType.
class ns1__Stato
{ public:
/// Element note of type xs:string.
    char*                                note                          ;	///< Nullable pointer.
/// Element tipo of type xs:int.
    int                                  tipo                           1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Step is a complexType.
class ns1__Step
{ public:
/// Element dataOraFine of type xs:dateTime.
    time_t*                              dataOraFine                   ;	///< Nullable pointer.
/// Element dataOraInizio of type xs:dateTime.
    time_t*                              dataOraInizio                 ;	///< Nullable pointer.
/// Element descrizione of type xs:string.
    char*                                descrizione                   ;	///< Nullable pointer.
/// Element esecutore of type xs:string.
    char*                                esecutore                     ;	///< Nullable pointer.
/// Element id of type xs:string.
    char*                                id                            ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":ArrayOfStep is a complexType.
class ns1__ArrayOfStep
{ public:
/// Size of array of ns1__Step* is 0..unbounded
   $int                                  __sizeitem                     0;
/// Pointer to array ns1__Step* of length 0..unbounded
    ns1__Step*                          *item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":ArrayOf_xsd_string is a complexType.
class ns1__ArrayOf_USCORExsd_USCOREstring
{ public:
/// Size of array of char* is 0..unbounded
   $int                                  __sizeitem                     0;
/// Pointer to array char* of length 0..unbounded
    char*                               *item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Esito is a complexType.
class ns1__Esito
{ public:
/// Element descrizione of type xs:string.
    char*                                descrizione                   ;	///< Nullable pointer.
/// Element valori of type "http://webapi.wfca.infocert.it":ArrayOf_xsd_string.
    ns1__ArrayOf_USCORExsd_USCOREstring*  valori                        ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Attributo is a complexType.
class ns1__Attributo
{ public:
/// Element nome of type xs:string.
    char*                                nome                          ;	///< Nullable pointer.
/// Element valore of type xs:string.
    char*                                valore                        ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":ArrayOfAttributo is a complexType.
class ns1__ArrayOfAttributo
{ public:
/// Size of array of ns1__Attributo* is 0..unbounded
   $int                                  __sizeitem                     0;
/// Pointer to array ns1__Attributo* of length 0..unbounded
    ns1__Attributo*                     *item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Funzione is a complexType.
class ns1__Funzione
{ public:
/// Element attributi of type "http://webapi.wfca.infocert.it":ArrayOfAttributo.
    ns1__ArrayOfAttributo*               attributi                     ;	///< Nullable pointer.
/// Element codice of type xs:string.
    char*                                codice                        ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":ArrayOfFunzione is a complexType.
class ns1__ArrayOfFunzione
{ public:
/// Size of array of ns1__Funzione* is 0..unbounded
   $int                                  __sizeitem                     0;
/// Pointer to array ns1__Funzione* of length 0..unbounded
    ns1__Funzione*                      *item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":ArrayOfStepCompetenza is a complexType.
class ns1__ArrayOfStepCompetenza
{ public:
/// Size of array of ns1__StepCompetenza* is 0..unbounded
   $int                                  __sizeitem                     0;
/// Pointer to array ns1__StepCompetenza* of length 0..unbounded
    ns1__StepCompetenza*                *item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Procedimento is a complexType.
class ns1__Procedimento
{ public:
/// Element dataOraFine of type xs:dateTime.
    time_t*                              dataOraFine                   ;	///< Nullable pointer.
/// Element dataOraInizio of type xs:dateTime.
    time_t*                              dataOraInizio                 ;	///< Nullable pointer.
/// Element descrizione of type xs:string.
    char*                                descrizione                   ;	///< Nullable pointer.
/// Element descrizioneOwner of type xs:string.
    char*                                descrizioneOwner              ;	///< Nullable pointer.
/// Element id of type xs:string.
    char*                                id                            ;	///< Nullable pointer.
/// Element note of type "http://webapi.wfca.infocert.it":ArrayOfNota.
    ns1__ArrayOfNota*                    note                          ;	///< Nullable pointer.
/// Element numeroRepertorio of type xs:string.
    char*                                numeroRepertorio              ;	///< Nullable pointer.
/// Element richiedente of type xs:string.
    char*                                richiedente                   ;	///< Nullable pointer.
/// Element stato of type "http://webapi.wfca.infocert.it":Stato.
    ns1__Stato*                          stato                         ;	///< Nullable pointer.
/// Element step of type "http://webapi.wfca.infocert.it":ArrayOfStep.
    ns1__ArrayOfStep*                    step                          ;	///< Nullable pointer.
/// Element stepCompetenza of type "http://webapi.wfca.infocert.it":ArrayOfStepCompetenza.
    ns1__ArrayOfStepCompetenza*          stepCompetenza                ;	///< Nullable pointer.
/// Element usernameOwner of type xs:string.
    char*                                usernameOwner                 ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Flusso is a complexType.
class ns1__Flusso
{ public:
/// Element codFlusso of type xs:string.
    char*                                codFlusso                     ;	///< Nullable pointer.
/// Element descrizione of type xs:string.
    char*                                descrizione                   ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":Giustificativo is a complexType.
class ns1__Giustificativo
{ public:
/// Element anno of type xs:string.
    char*                                anno                          ;	///< Nullable pointer.
/// Element codiceFlusso of type xs:string.
    char*                                codiceFlusso                  ;	///< Nullable pointer.
/// Element dataOraFine of type xs:dateTime.
    time_t*                              dataOraFine                   ;	///< Nullable pointer.
/// Element dataOraInizio of type xs:dateTime.
    time_t*                              dataOraInizio                 ;	///< Nullable pointer.
/// Element esito of type xs:string.
    char*                                esito                         ;	///< Nullable pointer.
/// Element idDocumento of type xs:long.
    LONG64                               idDocumento                    1;	///< Required element.
/// Element idFascicolo of type xs:long.
    LONG64                               idFascicolo                    1;	///< Required element.
/// Element mese of type xs:string.
    char*                                mese                          ;	///< Nullable pointer.
/// Element nominativo of type xs:string.
    char*                                nominativo                    ;	///< Nullable pointer.
/// Element username of type xs:string.
    char*                                username                      ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getToken

/// "http://webapi.wfca.infocert.it":getToken is a complexType.
class _ns1__getToken
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element connectionIdMac of type xs:string.
    char*                                connectionIdMac                1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getTokenResponse

/// "http://webapi.wfca.infocert.it":getTokenResponse is a complexType.
class _ns1__getTokenResponse
{ public:
/// Element getTokenReturn of type xs:string.
    char*                                getTokenReturn                 1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":login

/// "http://webapi.wfca.infocert.it":login is a complexType.
class _ns1__login
{ public:
/// Element usrApp of type xs:string.
    char*                                usrApp                         1;	///< Required element.
/// Element pwdApp of type xs:string.
    char*                                pwdApp                         1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":loginResponse

/// "http://webapi.wfca.infocert.it":loginResponse is a complexType.
class _ns1__loginResponse
{ public:
/// Element loginReturn of type xs:string.
    char*                                loginReturn                    1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":attivaProcedimento

/// "http://webapi.wfca.infocert.it":attivaProcedimento is a complexType.
class _ns1__attivaProcedimento
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element username of type xs:string.
    char*                                username                       1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// Element codFlusso of type xs:string.
    char*                                codFlusso                      1;	///< Required element.
/// Element nomeDocumento of type xs:string.
    char*                                nomeDocumento                  1;	///< Required element.
/// Element nomeFile of type xs:string.
    char*                                nomeFile                       1;	///< Required element.
/// Size of array of ns1__MetaDato* is 1..unbounded
   $int                                  __sizemetaDatiDocumento        1;
/// Pointer to array ns1__MetaDato* of length 1..unbounded
    ns1__MetaDato*                      *metaDatiDocumento              1;
/// Size of array of ns1__MetaDato* is 1..unbounded
   $int                                  __sizemetaDatiProcedimento     1;
/// Pointer to array ns1__MetaDato* of length 1..unbounded
    ns1__MetaDato*                      *metaDatiProcedimento           1;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":attivaProcedimentoResponse

/// "http://webapi.wfca.infocert.it":attivaProcedimentoResponse is a complexType.
class _ns1__attivaProcedimentoResponse
{ public:
/// Element attivaProcedimentoReturn of type "http://webapi.wfca.infocert.it":Procedimento.
    ns1__Procedimento*                   attivaProcedimentoReturn       1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":attivaProcedimentoWide

/// "http://webapi.wfca.infocert.it":attivaProcedimentoWide is a complexType.
class _ns1__attivaProcedimentoWide
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element username of type xs:string.
    char*                                username                       1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// Element codFlusso of type xs:string.
    char*                                codFlusso                      1;	///< Required element.
/// Element idFascicoloWide of type xs:long.
    LONG64                               idFascicoloWide                1;	///< Required element.
/// Element idDocumentoWide of type xs:long.
    LONG64                               idDocumentoWide                1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":attivaProcedimentoWideResponse

/// "http://webapi.wfca.infocert.it":attivaProcedimentoWideResponse is a complexType.
class _ns1__attivaProcedimentoWideResponse
{ public:
/// Element attivaProcedimentoWideReturn of type "http://webapi.wfca.infocert.it":Procedimento.
    ns1__Procedimento*                   attivaProcedimentoWideReturn   1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":aggiungiDocumentoAlProcedimento

/// "http://webapi.wfca.infocert.it":aggiungiDocumentoAlProcedimento is a complexType.
class _ns1__aggiungiDocumentoAlProcedimento
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// Element idProcedimento of type xs:string.
    char*                                idProcedimento                 1;	///< Required element.
/// Element nomeDocumento of type xs:string.
    char*                                nomeDocumento                  1;	///< Required element.
/// Element nomeFile of type xs:string.
    char*                                nomeFile                       1;	///< Required element.
/// Size of array of ns1__MetaDato* is 1..unbounded
   $int                                  __sizemetaDatiDocumento        1;
/// Pointer to array ns1__MetaDato* of length 1..unbounded
    ns1__MetaDato*                      *metaDatiDocumento              1;
/// Element inAllegato of type xs:boolean.
    bool                                 inAllegato                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":aggiungiDocumentoAlProcedimentoResponse

/// "http://webapi.wfca.infocert.it":aggiungiDocumentoAlProcedimentoResponse is a complexType.
class _ns1__aggiungiDocumentoAlProcedimentoResponse
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getProcedimento

/// "http://webapi.wfca.infocert.it":getProcedimento is a complexType.
class _ns1__getProcedimento
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element username of type xs:string.
    char*                                username                       1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// Element idProcedimento of type xs:string.
    char*                                idProcedimento                 1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getProcedimentoResponse

/// "http://webapi.wfca.infocert.it":getProcedimentoResponse is a complexType.
class _ns1__getProcedimentoResponse
{ public:
/// Element getProcedimentoReturn of type "http://webapi.wfca.infocert.it":Procedimento.
    ns1__Procedimento*                   getProcedimentoReturn          1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":avanzaProcedimento

/// "http://webapi.wfca.infocert.it":avanzaProcedimento is a complexType.
class _ns1__avanzaProcedimento
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element username of type xs:string.
    char*                                username                       1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// Element idProcedimento of type xs:string.
    char*                                idProcedimento                 1;	///< Required element.
/// Element idStep of type xs:string.
    char*                                idStep                         1;	///< Required element.
/// Element valoreEsito of type xs:string.
    char*                                valoreEsito                    1;	///< Required element.
/// Element note of type xs:string.
    char*                                note                           1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":avanzaProcedimentoResponse

/// "http://webapi.wfca.infocert.it":avanzaProcedimentoResponse is a complexType.
class _ns1__avanzaProcedimentoResponse
{ public:
/// Element avanzaProcedimentoReturn of type "http://webapi.wfca.infocert.it":Procedimento.
    ns1__Procedimento*                   avanzaProcedimentoReturn       1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getFlussi

/// "http://webapi.wfca.infocert.it":getFlussi is a complexType.
class _ns1__getFlussi
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element username of type xs:string.
    char*                                username                       1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getFlussiResponse

/// "http://webapi.wfca.infocert.it":getFlussiResponse is a complexType.
class _ns1__getFlussiResponse
{ public:
/// Size of array of ns1__Flusso* is 1..unbounded
   $int                                  __sizegetFlussiReturn          1;
/// Pointer to array ns1__Flusso* of length 1..unbounded
    ns1__Flusso*                        *getFlussiReturn                1;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getGiustificativi

/// "http://webapi.wfca.infocert.it":getGiustificativi is a complexType.
class _ns1__getGiustificativi
{ public:
/// Element token of type xs:string.
    char*                                token                          1;	///< Required element.
/// Element anno of type xs:string.
    char*                                anno                           1;	///< Required element.
/// Element mese of type xs:string.
    char*                                mese                           1;	///< Required element.
/// Element esito of type xs:string.
    char*                                esito                          1;	///< Required element.
/// Element codiceFlusso of type xs:string.
    char*                                codiceFlusso                   1;	///< Required element.
/// Element idAmministrazione of type xs:long.
    LONG64                               idAmministrazione              1;	///< Required element.
/// Element idAoo of type xs:long.
    LONG64                               idAoo                          1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://webapi.wfca.infocert.it":getGiustificativiResponse

/// "http://webapi.wfca.infocert.it":getGiustificativiResponse is a complexType.
class _ns1__getGiustificativiResponse
{ public:
/// Size of array of ns1__Giustificativo* is 1..unbounded
   $int                                  __sizegetGiustificativiReturn  1;
/// Pointer to array ns1__Giustificativo* of length 1..unbounded
    ns1__Giustificativo*                *getGiustificativiReturn        1;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://webapi.wfca.infocert.it":StepCompetenza is a complexType with complexContent extension of "http://webapi.wfca.infocert.it":Step.
class ns1__StepCompetenza : public ns1__Step
{ public:
/*  INHERITED FROM ns1__Step:
/// Element dataOraFine of type xs:dateTime.
    time_t*                              dataOraFine                   ;	///< Nullable pointer.
/// Element dataOraInizio of type xs:dateTime.
    time_t*                              dataOraInizio                 ;	///< Nullable pointer.
/// Element descrizione of type xs:string.
    char*                                descrizione                   ;	///< Nullable pointer.
/// Element esecutore of type xs:string.
    char*                                esecutore                     ;	///< Nullable pointer.
/// Element id of type xs:string.
    char*                                id                            ;	///< Nullable pointer.
    END OF INHERITED FROM ns1__Step */
/// Element codiciFunzione of type "http://webapi.wfca.infocert.it":ArrayOf_xsd_string.
    ns1__ArrayOf_USCORExsd_USCOREstring*  codiciFunzione                ;	///< Nullable pointer.
/// Element esito of type "http://webapi.wfca.infocert.it":Esito.
    ns1__Esito*                          esito                         ;	///< Nullable pointer.
/// Element funzioni of type "http://webapi.wfca.infocert.it":ArrayOfFunzione.
    ns1__ArrayOfFunzione*                funzioni                      ;	///< Nullable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://webapi.wfca.infocert.it                                           *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://webapi.wfca.infocert.it":fault of type "http://webapi.wfca.infocert.it":EccezioneAutenticazione.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://webapi.wfca.infocert.it":fault1 of type "http://webapi.wfca.infocert.it":EccezioneSistema.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://webapi.wfca.infocert.it                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	WebApiSoapBinding 
//gsoap ns1  service type:	WebApi 
//gsoap ns1  service port:	http://www.legalcyclecl.infocert.it/wfca/services/WebApi 
//gsoap ns1  service namespace:	http://webapi.wfca.infocert.it 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref WebApiSoapBinding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page WebApiSoapBinding Binding "WebApiSoapBinding"

@section WebApiSoapBinding_operations Operations of Binding  "WebApiSoapBinding"

  - @ref __ns1__getToken

  - @ref __ns1__login

  - @ref __ns1__attivaProcedimento

  - @ref __ns1__attivaProcedimentoWide

  - @ref __ns1__aggiungiDocumentoAlProcedimento

  - @ref __ns1__getProcedimento

  - @ref __ns1__avanzaProcedimento

  - @ref __ns1__getFlussi

  - @ref __ns1__getGiustificativi

@section WebApiSoapBinding_ports Endpoints of Binding  "WebApiSoapBinding"

  - http://www.legalcyclecl.infocert.it/wfca/services/WebApi

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * SOAP Fault Detail                                                          *
 *                                                                            *
\******************************************************************************/

/**

The SOAP Fault is part of the gSOAP context and its content is accessed
through the soap.fault->detail variable (SOAP 1.1) or the
soap.fault->SOAP_ENV__Detail variable (SOAP 1.2).
Use option -j to omit.

*/
struct SOAP_ENV__Detail
{
// xsd:anyAttribute omitted: to parse attribute content of the Detail element into DOM anyAttribute, use wsdl2h option -d.
    _XML                                 __any                         ;	///< Catch any element content in XML string.
    ns1__EccezioneAutenticazione*        ns1__fault                    ;
///< SOAP Fault element ""http://webapi.wfca.infocert.it":fault" part "fault"
    ns1__EccezioneSistema*               ns1__fault1                   ;
///< SOAP Fault element ""http://webapi.wfca.infocert.it":fault1" part "fault1"
    int                                  __type                        ;	///< set to SOAP_TYPE_X for a serializable type X
    void                                *fault                         ;	///< points to serializable object X or NULL
};

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   WebApiSoapBinding                                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getToken                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getToken" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getToken(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__getToken*                     ns1__getToken,
    // response parameters:
    _ns1__getTokenResponse*             ns1__getTokenResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getToken(
    struct soap *soap,
    // request parameters:
    _ns1__getToken*                     ns1__getToken,
    // response parameters:
    _ns1__getTokenResponse*             ns1__getTokenResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	getToken document
//gsoap ns1  service method-encoding:	getToken literal
//gsoap ns1  service method-action:	getToken ""
//gsoap ns1  service method-fault:	getToken ns1__fault
int __ns1__getToken(
    _ns1__getToken*                     ns1__getToken,	///< Request parameter
    _ns1__getTokenResponse*             ns1__getTokenResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__login                                                             *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__login" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__login(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__login*                        ns1__login,
    // response parameters:
    _ns1__loginResponse*                ns1__loginResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__login(
    struct soap *soap,
    // request parameters:
    _ns1__login*                        ns1__login,
    // response parameters:
    _ns1__loginResponse*                ns1__loginResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	login document
//gsoap ns1  service method-encoding:	login literal
//gsoap ns1  service method-action:	login ""
//gsoap ns1  service method-fault:	login ns1__fault1
//gsoap ns1  service method-fault:	login ns1__fault
int __ns1__login(
    _ns1__login*                        ns1__login,	///< Request parameter
    _ns1__loginResponse*                ns1__loginResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__attivaProcedimento                                                *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__attivaProcedimento" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__attivaProcedimento(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__attivaProcedimento*           ns1__attivaProcedimento,
    // response parameters:
    _ns1__attivaProcedimentoResponse*   ns1__attivaProcedimentoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__attivaProcedimento(
    struct soap *soap,
    // request parameters:
    _ns1__attivaProcedimento*           ns1__attivaProcedimento,
    // response parameters:
    _ns1__attivaProcedimentoResponse*   ns1__attivaProcedimentoResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	attivaProcedimento document
//gsoap ns1  service method-encoding:	attivaProcedimento literal
//gsoap ns1  service method-action:	attivaProcedimento ""
//gsoap ns1  service method-fault:	attivaProcedimento ns1__fault1
//gsoap ns1  service method-fault:	attivaProcedimento ns1__fault
int __ns1__attivaProcedimento(
    _ns1__attivaProcedimento*           ns1__attivaProcedimento,	///< Request parameter
    _ns1__attivaProcedimentoResponse*   ns1__attivaProcedimentoResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__attivaProcedimentoWide                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__attivaProcedimentoWide" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__attivaProcedimentoWide(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__attivaProcedimentoWide*       ns1__attivaProcedimentoWide,
    // response parameters:
    _ns1__attivaProcedimentoWideResponse* ns1__attivaProcedimentoWideResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__attivaProcedimentoWide(
    struct soap *soap,
    // request parameters:
    _ns1__attivaProcedimentoWide*       ns1__attivaProcedimentoWide,
    // response parameters:
    _ns1__attivaProcedimentoWideResponse* ns1__attivaProcedimentoWideResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	attivaProcedimentoWide document
//gsoap ns1  service method-encoding:	attivaProcedimentoWide literal
//gsoap ns1  service method-action:	attivaProcedimentoWide ""
//gsoap ns1  service method-fault:	attivaProcedimentoWide ns1__fault1
//gsoap ns1  service method-fault:	attivaProcedimentoWide ns1__fault
int __ns1__attivaProcedimentoWide(
    _ns1__attivaProcedimentoWide*       ns1__attivaProcedimentoWide,	///< Request parameter
    _ns1__attivaProcedimentoWideResponse* ns1__attivaProcedimentoWideResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__aggiungiDocumentoAlProcedimento                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__aggiungiDocumentoAlProcedimento" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__aggiungiDocumentoAlProcedimento(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__aggiungiDocumentoAlProcedimento* ns1__aggiungiDocumentoAlProcedimento,
    // response parameters:
    _ns1__aggiungiDocumentoAlProcedimentoResponse* ns1__aggiungiDocumentoAlProcedimentoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__aggiungiDocumentoAlProcedimento(
    struct soap *soap,
    // request parameters:
    _ns1__aggiungiDocumentoAlProcedimento* ns1__aggiungiDocumentoAlProcedimento,
    // response parameters:
    _ns1__aggiungiDocumentoAlProcedimentoResponse* ns1__aggiungiDocumentoAlProcedimentoResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	aggiungiDocumentoAlProcedimento document
//gsoap ns1  service method-encoding:	aggiungiDocumentoAlProcedimento literal
//gsoap ns1  service method-action:	aggiungiDocumentoAlProcedimento ""
//gsoap ns1  service method-fault:	aggiungiDocumentoAlProcedimento ns1__fault1
//gsoap ns1  service method-fault:	aggiungiDocumentoAlProcedimento ns1__fault
int __ns1__aggiungiDocumentoAlProcedimento(
    _ns1__aggiungiDocumentoAlProcedimento* ns1__aggiungiDocumentoAlProcedimento,	///< Request parameter
    _ns1__aggiungiDocumentoAlProcedimentoResponse* ns1__aggiungiDocumentoAlProcedimentoResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getProcedimento                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getProcedimento" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getProcedimento(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__getProcedimento*              ns1__getProcedimento,
    // response parameters:
    _ns1__getProcedimentoResponse*      ns1__getProcedimentoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getProcedimento(
    struct soap *soap,
    // request parameters:
    _ns1__getProcedimento*              ns1__getProcedimento,
    // response parameters:
    _ns1__getProcedimentoResponse*      ns1__getProcedimentoResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	getProcedimento document
//gsoap ns1  service method-encoding:	getProcedimento literal
//gsoap ns1  service method-action:	getProcedimento ""
//gsoap ns1  service method-fault:	getProcedimento ns1__fault1
//gsoap ns1  service method-fault:	getProcedimento ns1__fault
int __ns1__getProcedimento(
    _ns1__getProcedimento*              ns1__getProcedimento,	///< Request parameter
    _ns1__getProcedimentoResponse*      ns1__getProcedimentoResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__avanzaProcedimento                                                *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__avanzaProcedimento" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__avanzaProcedimento(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__avanzaProcedimento*           ns1__avanzaProcedimento,
    // response parameters:
    _ns1__avanzaProcedimentoResponse*   ns1__avanzaProcedimentoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__avanzaProcedimento(
    struct soap *soap,
    // request parameters:
    _ns1__avanzaProcedimento*           ns1__avanzaProcedimento,
    // response parameters:
    _ns1__avanzaProcedimentoResponse*   ns1__avanzaProcedimentoResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	avanzaProcedimento document
//gsoap ns1  service method-encoding:	avanzaProcedimento literal
//gsoap ns1  service method-action:	avanzaProcedimento ""
//gsoap ns1  service method-fault:	avanzaProcedimento ns1__fault1
//gsoap ns1  service method-fault:	avanzaProcedimento ns1__fault
int __ns1__avanzaProcedimento(
    _ns1__avanzaProcedimento*           ns1__avanzaProcedimento,	///< Request parameter
    _ns1__avanzaProcedimentoResponse*   ns1__avanzaProcedimentoResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getFlussi                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getFlussi" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getFlussi(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__getFlussi*                    ns1__getFlussi,
    // response parameters:
    _ns1__getFlussiResponse*            ns1__getFlussiResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getFlussi(
    struct soap *soap,
    // request parameters:
    _ns1__getFlussi*                    ns1__getFlussi,
    // response parameters:
    _ns1__getFlussiResponse*            ns1__getFlussiResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	getFlussi document
//gsoap ns1  service method-encoding:	getFlussi literal
//gsoap ns1  service method-action:	getFlussi ""
//gsoap ns1  service method-fault:	getFlussi ns1__fault1
//gsoap ns1  service method-fault:	getFlussi ns1__fault
int __ns1__getFlussi(
    _ns1__getFlussi*                    ns1__getFlussi,	///< Request parameter
    _ns1__getFlussiResponse*            ns1__getFlussiResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getGiustificativi                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getGiustificativi" of service binding "WebApiSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault1 (literal)

  - SOAP Fault: "http://webapi.wfca.infocert.it":fault (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getGiustificativi(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__getGiustificativi*            ns1__getGiustificativi,
    // response parameters:
    _ns1__getGiustificativiResponse*    ns1__getGiustificativiResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getGiustificativi(
    struct soap *soap,
    // request parameters:
    _ns1__getGiustificativi*            ns1__getGiustificativi,
    // response parameters:
    _ns1__getGiustificativiResponse*    ns1__getGiustificativiResponse
  );
@endcode

C++ proxy class (defined in soapWebApiSoapBindingProxy.h):
@code
  class WebApiSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapWebApiSoapBindingService.h):
@code
  class WebApiSoapBindingService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-style:	getGiustificativi document
//gsoap ns1  service method-encoding:	getGiustificativi literal
//gsoap ns1  service method-action:	getGiustificativi ""
//gsoap ns1  service method-fault:	getGiustificativi ns1__fault1
//gsoap ns1  service method-fault:	getGiustificativi ns1__fault
int __ns1__getGiustificativi(
    _ns1__getGiustificativi*            ns1__getGiustificativi,	///< Request parameter
    _ns1__getGiustificativiResponse*    ns1__getGiustificativiResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "http://webapi.wfca.infocert.it"

  - <ns1:getToken> @ref _ns1__getToken
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getToken(struct soap*, _ns1__getToken*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getToken(struct soap*, _ns1__getToken*);
    @endcode

  - <ns1:getTokenResponse> @ref _ns1__getTokenResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getTokenResponse(struct soap*, _ns1__getTokenResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getTokenResponse(struct soap*, _ns1__getTokenResponse*);
    @endcode

  - <ns1:fault> (use wsdl2h option -g to auto-generate)

  - <ns1:login> @ref _ns1__login
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__login(struct soap*, _ns1__login*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__login(struct soap*, _ns1__login*);
    @endcode

  - <ns1:loginResponse> @ref _ns1__loginResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__loginResponse(struct soap*, _ns1__loginResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__loginResponse(struct soap*, _ns1__loginResponse*);
    @endcode

  - <ns1:fault1> (use wsdl2h option -g to auto-generate)

  - <ns1:attivaProcedimento> @ref _ns1__attivaProcedimento
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__attivaProcedimento(struct soap*, _ns1__attivaProcedimento*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__attivaProcedimento(struct soap*, _ns1__attivaProcedimento*);
    @endcode

  - <ns1:attivaProcedimentoResponse> @ref _ns1__attivaProcedimentoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__attivaProcedimentoResponse(struct soap*, _ns1__attivaProcedimentoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__attivaProcedimentoResponse(struct soap*, _ns1__attivaProcedimentoResponse*);
    @endcode

  - <ns1:attivaProcedimentoWide> @ref _ns1__attivaProcedimentoWide
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__attivaProcedimentoWide(struct soap*, _ns1__attivaProcedimentoWide*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__attivaProcedimentoWide(struct soap*, _ns1__attivaProcedimentoWide*);
    @endcode

  - <ns1:attivaProcedimentoWideResponse> @ref _ns1__attivaProcedimentoWideResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__attivaProcedimentoWideResponse(struct soap*, _ns1__attivaProcedimentoWideResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__attivaProcedimentoWideResponse(struct soap*, _ns1__attivaProcedimentoWideResponse*);
    @endcode

  - <ns1:aggiungiDocumentoAlProcedimento> @ref _ns1__aggiungiDocumentoAlProcedimento
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__aggiungiDocumentoAlProcedimento(struct soap*, _ns1__aggiungiDocumentoAlProcedimento*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__aggiungiDocumentoAlProcedimento(struct soap*, _ns1__aggiungiDocumentoAlProcedimento*);
    @endcode

  - <ns1:aggiungiDocumentoAlProcedimentoResponse> @ref _ns1__aggiungiDocumentoAlProcedimentoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__aggiungiDocumentoAlProcedimentoResponse(struct soap*, _ns1__aggiungiDocumentoAlProcedimentoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__aggiungiDocumentoAlProcedimentoResponse(struct soap*, _ns1__aggiungiDocumentoAlProcedimentoResponse*);
    @endcode

  - <ns1:getProcedimento> @ref _ns1__getProcedimento
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getProcedimento(struct soap*, _ns1__getProcedimento*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getProcedimento(struct soap*, _ns1__getProcedimento*);
    @endcode

  - <ns1:getProcedimentoResponse> @ref _ns1__getProcedimentoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getProcedimentoResponse(struct soap*, _ns1__getProcedimentoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getProcedimentoResponse(struct soap*, _ns1__getProcedimentoResponse*);
    @endcode

  - <ns1:avanzaProcedimento> @ref _ns1__avanzaProcedimento
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__avanzaProcedimento(struct soap*, _ns1__avanzaProcedimento*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__avanzaProcedimento(struct soap*, _ns1__avanzaProcedimento*);
    @endcode

  - <ns1:avanzaProcedimentoResponse> @ref _ns1__avanzaProcedimentoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__avanzaProcedimentoResponse(struct soap*, _ns1__avanzaProcedimentoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__avanzaProcedimentoResponse(struct soap*, _ns1__avanzaProcedimentoResponse*);
    @endcode

  - <ns1:getFlussi> @ref _ns1__getFlussi
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getFlussi(struct soap*, _ns1__getFlussi*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getFlussi(struct soap*, _ns1__getFlussi*);
    @endcode

  - <ns1:getFlussiResponse> @ref _ns1__getFlussiResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getFlussiResponse(struct soap*, _ns1__getFlussiResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getFlussiResponse(struct soap*, _ns1__getFlussiResponse*);
    @endcode

  - <ns1:getGiustificativi> @ref _ns1__getGiustificativi
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getGiustificativi(struct soap*, _ns1__getGiustificativi*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getGiustificativi(struct soap*, _ns1__getGiustificativi*);
    @endcode

  - <ns1:getGiustificativiResponse> @ref _ns1__getGiustificativiResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getGiustificativiResponse(struct soap*, _ns1__getGiustificativiResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getGiustificativiResponse(struct soap*, _ns1__getGiustificativiResponse*);
    @endcode

*/

/* End of WebApi.h */
