//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAIRClient.DatiPaziente {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class AIRApplicationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class patientComplications : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime amputationField;
        
        private bool amputationFieldSpecified;
        
        private System.DateTime anginaField;
        
        private bool anginaFieldSpecified;
        
        private System.DateTime blindnessField;
        
        private bool blindnessFieldSpecified;
        
        private string citizenIdField;
        
        private System.DateTime claudicatioField;
        
        private bool claudicatioFieldSpecified;
        
        private System.DateTime dialysisField;
        
        private bool dialysisFieldSpecified;
        
        private System.DateTime fundusField;
        
        private bool fundusFieldSpecified;
        
        private System.DateTime ictusField;
        
        private bool ictusFieldSpecified;
        
        private System.DateTime imaField;
        
        private bool imaFieldSpecified;
        
        private System.DateTime ischemicHeartConditionField;
        
        private bool ischemicHeartConditionFieldSpecified;
        
        private System.DateTime nephropathyField;
        
        private bool nephropathyFieldSpecified;
        
        private System.DateTime retinopathyField;
        
        private bool retinopathyFieldSpecified;
        
        private System.DateTime revascularizationField;
        
        private bool revascularizationFieldSpecified;
        
        private System.DateTime tiaField;
        
        private bool tiaFieldSpecified;
        
        private System.DateTime ulcerationsField;
        
        private bool ulcerationsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime amputation {
            get {
                return this.amputationField;
            }
            set {
                this.amputationField = value;
                this.RaisePropertyChanged("amputation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amputationSpecified {
            get {
                return this.amputationFieldSpecified;
            }
            set {
                this.amputationFieldSpecified = value;
                this.RaisePropertyChanged("amputationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime angina {
            get {
                return this.anginaField;
            }
            set {
                this.anginaField = value;
                this.RaisePropertyChanged("angina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anginaSpecified {
            get {
                return this.anginaFieldSpecified;
            }
            set {
                this.anginaFieldSpecified = value;
                this.RaisePropertyChanged("anginaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime blindness {
            get {
                return this.blindnessField;
            }
            set {
                this.blindnessField = value;
                this.RaisePropertyChanged("blindness");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool blindnessSpecified {
            get {
                return this.blindnessFieldSpecified;
            }
            set {
                this.blindnessFieldSpecified = value;
                this.RaisePropertyChanged("blindnessSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string citizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("citizenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime claudicatio {
            get {
                return this.claudicatioField;
            }
            set {
                this.claudicatioField = value;
                this.RaisePropertyChanged("claudicatio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool claudicatioSpecified {
            get {
                return this.claudicatioFieldSpecified;
            }
            set {
                this.claudicatioFieldSpecified = value;
                this.RaisePropertyChanged("claudicatioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime dialysis {
            get {
                return this.dialysisField;
            }
            set {
                this.dialysisField = value;
                this.RaisePropertyChanged("dialysis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dialysisSpecified {
            get {
                return this.dialysisFieldSpecified;
            }
            set {
                this.dialysisFieldSpecified = value;
                this.RaisePropertyChanged("dialysisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fundus {
            get {
                return this.fundusField;
            }
            set {
                this.fundusField = value;
                this.RaisePropertyChanged("fundus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fundusSpecified {
            get {
                return this.fundusFieldSpecified;
            }
            set {
                this.fundusFieldSpecified = value;
                this.RaisePropertyChanged("fundusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime ictus {
            get {
                return this.ictusField;
            }
            set {
                this.ictusField = value;
                this.RaisePropertyChanged("ictus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ictusSpecified {
            get {
                return this.ictusFieldSpecified;
            }
            set {
                this.ictusFieldSpecified = value;
                this.RaisePropertyChanged("ictusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime ima {
            get {
                return this.imaField;
            }
            set {
                this.imaField = value;
                this.RaisePropertyChanged("ima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imaSpecified {
            get {
                return this.imaFieldSpecified;
            }
            set {
                this.imaFieldSpecified = value;
                this.RaisePropertyChanged("imaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime ischemicHeartCondition {
            get {
                return this.ischemicHeartConditionField;
            }
            set {
                this.ischemicHeartConditionField = value;
                this.RaisePropertyChanged("ischemicHeartCondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ischemicHeartConditionSpecified {
            get {
                return this.ischemicHeartConditionFieldSpecified;
            }
            set {
                this.ischemicHeartConditionFieldSpecified = value;
                this.RaisePropertyChanged("ischemicHeartConditionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime nephropathy {
            get {
                return this.nephropathyField;
            }
            set {
                this.nephropathyField = value;
                this.RaisePropertyChanged("nephropathy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nephropathySpecified {
            get {
                return this.nephropathyFieldSpecified;
            }
            set {
                this.nephropathyFieldSpecified = value;
                this.RaisePropertyChanged("nephropathySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime retinopathy {
            get {
                return this.retinopathyField;
            }
            set {
                this.retinopathyField = value;
                this.RaisePropertyChanged("retinopathy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retinopathySpecified {
            get {
                return this.retinopathyFieldSpecified;
            }
            set {
                this.retinopathyFieldSpecified = value;
                this.RaisePropertyChanged("retinopathySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public System.DateTime revascularization {
            get {
                return this.revascularizationField;
            }
            set {
                this.revascularizationField = value;
                this.RaisePropertyChanged("revascularization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revascularizationSpecified {
            get {
                return this.revascularizationFieldSpecified;
            }
            set {
                this.revascularizationFieldSpecified = value;
                this.RaisePropertyChanged("revascularizationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime tia {
            get {
                return this.tiaField;
            }
            set {
                this.tiaField = value;
                this.RaisePropertyChanged("tia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiaSpecified {
            get {
                return this.tiaFieldSpecified;
            }
            set {
                this.tiaFieldSpecified = value;
                this.RaisePropertyChanged("tiaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime ulcerations {
            get {
                return this.ulcerationsField;
            }
            set {
                this.ulcerationsField = value;
                this.RaisePropertyChanged("ulcerations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ulcerationsSpecified {
            get {
                return this.ulcerationsFieldSpecified;
            }
            set {
                this.ulcerationsFieldSpecified = value;
                this.RaisePropertyChanged("ulcerationsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class authorizationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class IllegalArgumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class DataValidationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://air.di.unisa.it/", ConfigurationName="DatiPaziente.PatientDataWebService")]
    public interface PatientDataWebService {
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.AIRApplicationException), Action="", Name="AIRApplicationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.IllegalArgumentException), Action="", Name="IllegalArgumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.DataValidationException), Action="", Name="DataValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAIRClient.DatiPaziente.doWriteComplicationsResponse doWriteComplications(TestAIRClient.DatiPaziente.doWriteComplications request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.AIRApplicationException), Action="", Name="AIRApplicationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.IllegalArgumentException), Action="", Name="IllegalArgumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.DataValidationException), Action="", Name="DataValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAIRClient.DatiPaziente.doWriteExemptionCodeResponse doWriteExemptionCode(TestAIRClient.DatiPaziente.doWriteExemptionCode request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAIRClient.DatiPaziente.getVersionResponse getVersion(TestAIRClient.DatiPaziente.getVersion request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.AIRApplicationException), Action="", Name="AIRApplicationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.IllegalArgumentException), Action="", Name="IllegalArgumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.DataValidationException), Action="", Name="DataValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAIRClient.DatiPaziente.doWriteAnagraficDataResponse doWriteAnagraficData(TestAIRClient.DatiPaziente.doWriteAnagraficData request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.AIRApplicationException), Action="", Name="AIRApplicationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.DataValidationException), Action="", Name="DataValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAIRClient.DatiPaziente.getAuthorizationTokenResponse getAuthorizationToken(TestAIRClient.DatiPaziente.getAuthorizationToken request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.AIRApplicationException), Action="", Name="AIRApplicationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.IllegalArgumentException), Action="", Name="IllegalArgumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestAIRClient.DatiPaziente.DataValidationException), Action="", Name="DataValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAIRClient.DatiPaziente.doWriteAnamnesticDataResponse doWriteAnamnesticData(TestAIRClient.DatiPaziente.doWriteAnamnesticData request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteComplications", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteComplications {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.authorizationToken securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MMGCodFisc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.patientComplications patientComplications;
        
        public doWriteComplications() {
        }
        
        public doWriteComplications(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientComplications patientComplications) {
            this.securityToken = securityToken;
            this.MMGCodFisc = MMGCodFisc;
            this.patientComplications = patientComplications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteComplicationsResponse", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteComplicationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public doWriteComplicationsResponse() {
        }
        
        public doWriteComplicationsResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class patientExemption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string citizenIdField;
        
        private string exemptionCodeField;
        
        private System.Nullable<System.DateTime> exemptionDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string citizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("citizenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exemptionCode {
            get {
                return this.exemptionCodeField;
            }
            set {
                this.exemptionCodeField = value;
                this.RaisePropertyChanged("exemptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> exemptionDate {
            get {
                return this.exemptionDateField;
            }
            set {
                this.exemptionDateField = value;
                this.RaisePropertyChanged("exemptionDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteExemptionCode", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteExemptionCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.authorizationToken securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MMGCodFisc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.patientExemption patientExemption;
        
        public doWriteExemptionCode() {
        }
        
        public doWriteExemptionCode(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientExemption patientExemption) {
            this.securityToken = securityToken;
            this.MMGCodFisc = MMGCodFisc;
            this.patientExemption = patientExemption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteExemptionCodeResponse", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteExemptionCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public doWriteExemptionCodeResponse() {
        }
        
        public doWriteExemptionCodeResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class getVersion {
        
        public getVersion() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class patientAnagraficData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aslField;
        
        private System.Nullable<System.DateTime> birthdateField;
        
        private string cityField;
        
        private string citizenIdField;
        
        private int dsbField;
        
        private string houseNumberField;
        
        private string nameField;
        
        private string nationalityField;
        
        private string roadField;
        
        private string patientCodFiscField;
        
        private string surnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int asl {
            get {
                return this.aslField;
            }
            set {
                this.aslField = value;
                this.RaisePropertyChanged("asl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
                this.RaisePropertyChanged("birthdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string citizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("citizenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int dsb {
            get {
                return this.dsbField;
            }
            set {
                this.dsbField = value;
                this.RaisePropertyChanged("dsb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("houseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string road {
            get {
                return this.roadField;
            }
            set {
                this.roadField = value;
                this.RaisePropertyChanged("road");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string patientCodFisc {
            get {
                return this.patientCodFiscField;
            }
            set {
                this.patientCodFiscField = value;
                this.RaisePropertyChanged("patientCodFisc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class patientAnagraficDataResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string citizenIdField;
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string citizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("citizenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteAnagraficData", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteAnagraficData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.authorizationToken securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MMGCodFisc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.patientAnagraficData patientAnagraficData;
        
        public doWriteAnagraficData() {
        }
        
        public doWriteAnagraficData(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientAnagraficData patientAnagraficData) {
            this.securityToken = securityToken;
            this.MMGCodFisc = MMGCodFisc;
            this.patientAnagraficData = patientAnagraficData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteAnagraficDataResponse", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteAnagraficDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.patientAnagraficDataResult @return;
        
        public doWriteAnagraficDataResponse() {
        }
        
        public doWriteAnagraficDataResponse(TestAIRClient.DatiPaziente.patientAnagraficDataResult @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class authenticationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientSecretField;
        
        private string passwordField;
        
        private string roleField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientSecret {
            get {
                return this.clientSecretField;
            }
            set {
                this.clientSecretField = value;
                this.RaisePropertyChanged("clientSecret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAuthorizationToken", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class getAuthorizationToken {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MMGCodFisc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.authenticationToken AuthenticationToken;
        
        public getAuthorizationToken() {
        }
        
        public getAuthorizationToken(string MMGCodFisc, TestAIRClient.DatiPaziente.authenticationToken AuthenticationToken) {
            this.MMGCodFisc = MMGCodFisc;
            this.AuthenticationToken = AuthenticationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAuthorizationTokenResponse", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class getAuthorizationTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.authorizationToken @return;
        
        public getAuthorizationTokenResponse() {
        }
        
        public getAuthorizationTokenResponse(TestAIRClient.DatiPaziente.authorizationToken @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://air.di.unisa.it/")]
    public partial class patientAnamnesticData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime alcoholCheckDateField;
        
        private bool alcoholCheckDateFieldSpecified;
        
        private int alcoholKindField;
        
        private int alcoholQuantityField;
        
        private string citizenIdField;
        
        private int currentTherapyField;
        
        private int educationLevelField;
        
        private System.DateTime enrollDateField;
        
        private bool enrollDateFieldSpecified;
        
        private int firstDiabetesDiagnosisField;
        
        private int marital_statusField;
        
        private bool physicalActivityField;
        
        private System.DateTime physicalActivityCheckDateField;
        
        private bool physicalActivityCheckDateFieldSpecified;
        
        private int physicalActivityLevelField;
        
        private System.DateTime smokingCheckDateField;
        
        private bool smokingCheckDateFieldSpecified;
        
        private bool smokingCurrentAttitudeField;
        
        private int smokingDailyQuantityField;
        
        private int smokingLastYearField;
        
        private bool smokingPreviousAttitudeField;
        
        private int smokingTypeField;
        
        private bool alcoholUserField;
        
        private int workingCategoryField;
        
        private int workingPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime alcoholCheckDate {
            get {
                return this.alcoholCheckDateField;
            }
            set {
                this.alcoholCheckDateField = value;
                this.RaisePropertyChanged("alcoholCheckDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alcoholCheckDateSpecified {
            get {
                return this.alcoholCheckDateFieldSpecified;
            }
            set {
                this.alcoholCheckDateFieldSpecified = value;
                this.RaisePropertyChanged("alcoholCheckDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int alcoholKind {
            get {
                return this.alcoholKindField;
            }
            set {
                this.alcoholKindField = value;
                this.RaisePropertyChanged("alcoholKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int alcoholQuantity {
            get {
                return this.alcoholQuantityField;
            }
            set {
                this.alcoholQuantityField = value;
                this.RaisePropertyChanged("alcoholQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string citizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("citizenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int currentTherapy {
            get {
                return this.currentTherapyField;
            }
            set {
                this.currentTherapyField = value;
                this.RaisePropertyChanged("currentTherapy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int educationLevel {
            get {
                return this.educationLevelField;
            }
            set {
                this.educationLevelField = value;
                this.RaisePropertyChanged("educationLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime enrollDate {
            get {
                return this.enrollDateField;
            }
            set {
                this.enrollDateField = value;
                this.RaisePropertyChanged("enrollDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enrollDateSpecified {
            get {
                return this.enrollDateFieldSpecified;
            }
            set {
                this.enrollDateFieldSpecified = value;
                this.RaisePropertyChanged("enrollDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int firstDiabetesDiagnosis {
            get {
                return this.firstDiabetesDiagnosisField;
            }
            set {
                this.firstDiabetesDiagnosisField = value;
                this.RaisePropertyChanged("firstDiabetesDiagnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int marital_status {
            get {
                return this.marital_statusField;
            }
            set {
                this.marital_statusField = value;
                this.RaisePropertyChanged("marital_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool physicalActivity {
            get {
                return this.physicalActivityField;
            }
            set {
                this.physicalActivityField = value;
                this.RaisePropertyChanged("physicalActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime physicalActivityCheckDate {
            get {
                return this.physicalActivityCheckDateField;
            }
            set {
                this.physicalActivityCheckDateField = value;
                this.RaisePropertyChanged("physicalActivityCheckDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool physicalActivityCheckDateSpecified {
            get {
                return this.physicalActivityCheckDateFieldSpecified;
            }
            set {
                this.physicalActivityCheckDateFieldSpecified = value;
                this.RaisePropertyChanged("physicalActivityCheckDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int physicalActivityLevel {
            get {
                return this.physicalActivityLevelField;
            }
            set {
                this.physicalActivityLevelField = value;
                this.RaisePropertyChanged("physicalActivityLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public System.DateTime smokingCheckDate {
            get {
                return this.smokingCheckDateField;
            }
            set {
                this.smokingCheckDateField = value;
                this.RaisePropertyChanged("smokingCheckDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smokingCheckDateSpecified {
            get {
                return this.smokingCheckDateFieldSpecified;
            }
            set {
                this.smokingCheckDateFieldSpecified = value;
                this.RaisePropertyChanged("smokingCheckDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool smokingCurrentAttitude {
            get {
                return this.smokingCurrentAttitudeField;
            }
            set {
                this.smokingCurrentAttitudeField = value;
                this.RaisePropertyChanged("smokingCurrentAttitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int smokingDailyQuantity {
            get {
                return this.smokingDailyQuantityField;
            }
            set {
                this.smokingDailyQuantityField = value;
                this.RaisePropertyChanged("smokingDailyQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int smokingLastYear {
            get {
                return this.smokingLastYearField;
            }
            set {
                this.smokingLastYearField = value;
                this.RaisePropertyChanged("smokingLastYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public bool smokingPreviousAttitude {
            get {
                return this.smokingPreviousAttitudeField;
            }
            set {
                this.smokingPreviousAttitudeField = value;
                this.RaisePropertyChanged("smokingPreviousAttitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int smokingType {
            get {
                return this.smokingTypeField;
            }
            set {
                this.smokingTypeField = value;
                this.RaisePropertyChanged("smokingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public bool alcoholUser {
            get {
                return this.alcoholUserField;
            }
            set {
                this.alcoholUserField = value;
                this.RaisePropertyChanged("alcoholUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int workingCategory {
            get {
                return this.workingCategoryField;
            }
            set {
                this.workingCategoryField = value;
                this.RaisePropertyChanged("workingCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int workingPosition {
            get {
                return this.workingPositionField;
            }
            set {
                this.workingPositionField = value;
                this.RaisePropertyChanged("workingPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteAnamnesticData", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteAnamnesticData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.authorizationToken securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MMGCodFisc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAIRClient.DatiPaziente.patientAnamnesticData patientAnamnesticData;
        
        public doWriteAnamnesticData() {
        }
        
        public doWriteAnamnesticData(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientAnamnesticData patientAnamnesticData) {
            this.securityToken = securityToken;
            this.MMGCodFisc = MMGCodFisc;
            this.patientAnamnesticData = patientAnamnesticData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doWriteAnamnesticDataResponse", WrapperNamespace="http://air.di.unisa.it/", IsWrapped=true)]
    public partial class doWriteAnamnesticDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://air.di.unisa.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public doWriteAnamnesticDataResponse() {
        }
        
        public doWriteAnamnesticDataResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientDataWebServiceChannel : TestAIRClient.DatiPaziente.PatientDataWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientDataWebServiceClient : System.ServiceModel.ClientBase<TestAIRClient.DatiPaziente.PatientDataWebService>, TestAIRClient.DatiPaziente.PatientDataWebService {
        
        public PatientDataWebServiceClient() {
        }
        
        public PatientDataWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientDataWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientDataWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientDataWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAIRClient.DatiPaziente.doWriteComplicationsResponse TestAIRClient.DatiPaziente.PatientDataWebService.doWriteComplications(TestAIRClient.DatiPaziente.doWriteComplications request) {
            return base.Channel.doWriteComplications(request);
        }
        
        public bool doWriteComplications(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientComplications patientComplications) {
            TestAIRClient.DatiPaziente.doWriteComplications inValue = new TestAIRClient.DatiPaziente.doWriteComplications();
            inValue.securityToken = securityToken;
            inValue.MMGCodFisc = MMGCodFisc;
            inValue.patientComplications = patientComplications;
            TestAIRClient.DatiPaziente.doWriteComplicationsResponse retVal = ((TestAIRClient.DatiPaziente.PatientDataWebService)(this)).doWriteComplications(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAIRClient.DatiPaziente.doWriteExemptionCodeResponse TestAIRClient.DatiPaziente.PatientDataWebService.doWriteExemptionCode(TestAIRClient.DatiPaziente.doWriteExemptionCode request) {
            return base.Channel.doWriteExemptionCode(request);
        }
        
        public bool doWriteExemptionCode(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientExemption patientExemption) {
            TestAIRClient.DatiPaziente.doWriteExemptionCode inValue = new TestAIRClient.DatiPaziente.doWriteExemptionCode();
            inValue.securityToken = securityToken;
            inValue.MMGCodFisc = MMGCodFisc;
            inValue.patientExemption = patientExemption;
            TestAIRClient.DatiPaziente.doWriteExemptionCodeResponse retVal = ((TestAIRClient.DatiPaziente.PatientDataWebService)(this)).doWriteExemptionCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAIRClient.DatiPaziente.getVersionResponse TestAIRClient.DatiPaziente.PatientDataWebService.getVersion(TestAIRClient.DatiPaziente.getVersion request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            TestAIRClient.DatiPaziente.getVersion inValue = new TestAIRClient.DatiPaziente.getVersion();
            TestAIRClient.DatiPaziente.getVersionResponse retVal = ((TestAIRClient.DatiPaziente.PatientDataWebService)(this)).getVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAIRClient.DatiPaziente.doWriteAnagraficDataResponse TestAIRClient.DatiPaziente.PatientDataWebService.doWriteAnagraficData(TestAIRClient.DatiPaziente.doWriteAnagraficData request) {
            return base.Channel.doWriteAnagraficData(request);
        }
        
        public TestAIRClient.DatiPaziente.patientAnagraficDataResult doWriteAnagraficData(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientAnagraficData patientAnagraficData) {
            TestAIRClient.DatiPaziente.doWriteAnagraficData inValue = new TestAIRClient.DatiPaziente.doWriteAnagraficData();
            inValue.securityToken = securityToken;
            inValue.MMGCodFisc = MMGCodFisc;
            inValue.patientAnagraficData = patientAnagraficData;
            TestAIRClient.DatiPaziente.doWriteAnagraficDataResponse retVal = ((TestAIRClient.DatiPaziente.PatientDataWebService)(this)).doWriteAnagraficData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAIRClient.DatiPaziente.getAuthorizationTokenResponse TestAIRClient.DatiPaziente.PatientDataWebService.getAuthorizationToken(TestAIRClient.DatiPaziente.getAuthorizationToken request) {
            return base.Channel.getAuthorizationToken(request);
        }
        
        public TestAIRClient.DatiPaziente.authorizationToken getAuthorizationToken(string MMGCodFisc, TestAIRClient.DatiPaziente.authenticationToken AuthenticationToken) {
            TestAIRClient.DatiPaziente.getAuthorizationToken inValue = new TestAIRClient.DatiPaziente.getAuthorizationToken();
            inValue.MMGCodFisc = MMGCodFisc;
            inValue.AuthenticationToken = AuthenticationToken;
            TestAIRClient.DatiPaziente.getAuthorizationTokenResponse retVal = ((TestAIRClient.DatiPaziente.PatientDataWebService)(this)).getAuthorizationToken(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAIRClient.DatiPaziente.doWriteAnamnesticDataResponse TestAIRClient.DatiPaziente.PatientDataWebService.doWriteAnamnesticData(TestAIRClient.DatiPaziente.doWriteAnamnesticData request) {
            return base.Channel.doWriteAnamnesticData(request);
        }
        
        public bool doWriteAnamnesticData(TestAIRClient.DatiPaziente.authorizationToken securityToken, string MMGCodFisc, TestAIRClient.DatiPaziente.patientAnamnesticData patientAnamnesticData) {
            TestAIRClient.DatiPaziente.doWriteAnamnesticData inValue = new TestAIRClient.DatiPaziente.doWriteAnamnesticData();
            inValue.securityToken = securityToken;
            inValue.MMGCodFisc = MMGCodFisc;
            inValue.patientAnamnesticData = patientAnamnesticData;
            TestAIRClient.DatiPaziente.doWriteAnamnesticDataResponse retVal = ((TestAIRClient.DatiPaziente.PatientDataWebService)(this)).doWriteAnamnesticData(inValue);
            return retVal.@return;
        }
    }
}
