/*
 * Generated by XDoclet - Do not edit!
 */
package beans;

/**
 * Home interface for ScheduleSession.
 * @generated 
 * @wtp generated
 */
public interface ScheduleSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ScheduleSession";
   public static final String JNDI_NAME="ScheduleSession";

   public beans.ScheduleSession create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
