/*
 * Generated by XDoclet - Do not edit!
 */
package beans;

/**
 * Remote interface for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public interface ScheduleItem
   extends javax.ejb.EJBObject
{

}
