/*
 * Generated by XDoclet - Do not edit!
 */
package beans;

/**
 * Home interface for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public interface ScheduleItemHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ScheduleItem";
   public static final String JNDI_NAME="ScheduleItem";

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByScheduleID(java.lang.String scheduleID)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByName(java.lang.String name)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public beans.ScheduleItem findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
