/*
 * Generated by XDoclet - Do not edit!
 */
package beans;

/**
 * Data object for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public class ScheduleItemData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.Integer id;
   private java.lang.String name;
   private java.lang.Integer startTime;
   private java.lang.Integer endTime;
   private java.lang.Integer day;
   private java.lang.String scheduleID;

  /* begin value object */

  /* end value object */

   public ScheduleItemData()
   {
   }

   public ScheduleItemData( java.lang.Integer id,java.lang.String name,java.lang.Integer startTime,java.lang.Integer endTime,java.lang.Integer day,java.lang.String scheduleID )
   {
      setId(id);
      setName(name);
      setStartTime(startTime);
      setEndTime(endTime);
      setDay(day);
      setScheduleID(scheduleID);
   }

   public ScheduleItemData( ScheduleItemData otherData )
   {
      setId(otherData.getId());
      setName(otherData.getName());
      setStartTime(otherData.getStartTime());
      setEndTime(otherData.getEndTime());
      setDay(otherData.getDay());
      setScheduleID(otherData.getScheduleID());

   }

   public java.lang.Integer getPrimaryKey() {
     return  getId();
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }
   public void setId( java.lang.Integer id )
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }
   public void setName( java.lang.String name )
   {
      this.name = name;
   }

   public java.lang.Integer getStartTime()
   {
      return this.startTime;
   }
   public void setStartTime( java.lang.Integer startTime )
   {
      this.startTime = startTime;
   }

   public java.lang.Integer getEndTime()
   {
      return this.endTime;
   }
   public void setEndTime( java.lang.Integer endTime )
   {
      this.endTime = endTime;
   }

   public java.lang.Integer getDay()
   {
      return this.day;
   }
   public void setDay( java.lang.Integer day )
   {
      this.day = day;
   }

   public java.lang.String getScheduleID()
   {
      return this.scheduleID;
   }
   public void setScheduleID( java.lang.String scheduleID )
   {
      this.scheduleID = scheduleID;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("id=" + getId() + " " + "name=" + getName() + " " + "startTime=" + getStartTime() + " " + "endTime=" + getEndTime() + " " + "day=" + getDay() + " " + "scheduleID=" + getScheduleID());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof ScheduleItemData )
      {
         ScheduleItemData lTest = (ScheduleItemData) pOther;
         boolean lEquals = true;

         if( this.id == null )
         {
            lEquals = lEquals && ( lTest.id == null );
         }
         else
         {
            lEquals = lEquals && this.id.equals( lTest.id );
         }
         if( this.name == null )
         {
            lEquals = lEquals && ( lTest.name == null );
         }
         else
         {
            lEquals = lEquals && this.name.equals( lTest.name );
         }
         if( this.startTime == null )
         {
            lEquals = lEquals && ( lTest.startTime == null );
         }
         else
         {
            lEquals = lEquals && this.startTime.equals( lTest.startTime );
         }
         if( this.endTime == null )
         {
            lEquals = lEquals && ( lTest.endTime == null );
         }
         else
         {
            lEquals = lEquals && this.endTime.equals( lTest.endTime );
         }
         if( this.day == null )
         {
            lEquals = lEquals && ( lTest.day == null );
         }
         else
         {
            lEquals = lEquals && this.day.equals( lTest.day );
         }
         if( this.scheduleID == null )
         {
            lEquals = lEquals && ( lTest.scheduleID == null );
         }
         else
         {
            lEquals = lEquals && this.scheduleID.equals( lTest.scheduleID );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this.name != null) ? this.name.hashCode() : 0);

      result = 37*result + ((this.startTime != null) ? this.startTime.hashCode() : 0);

      result = 37*result + ((this.endTime != null) ? this.endTime.hashCode() : 0);

      result = 37*result + ((this.day != null) ? this.day.hashCode() : 0);

      result = 37*result + ((this.scheduleID != null) ? this.scheduleID.hashCode() : 0);

      return result;
   }

}
