/*
 * Generated by XDoclet - Do not edit!
 */
package beans;

/**
 * Local interface for ScheduleItem.
 * @generated 
 * @wtp generated
 */
public interface ScheduleItemLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-user-doc --> CMP Field id Returns the id
    * @return the id <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getId(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the id
    * @param java.lang.Integer the new id value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setId( java.lang.Integer id ) ;

   /**
    * <!-- begin-user-doc --> CMP Field name Returns the name
    * @return the name <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String getName(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the name
    * @param java.lang.String the new name value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setName( java.lang.String name ) ;

   /**
    * <!-- begin-user-doc --> CMP Field startTime Returns the startTime
    * @return the startTime <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getStartTime(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the startTime
    * @param java.lang.Integer the new startTime value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setStartTime( java.lang.Integer startTime ) ;

   /**
    * <!-- begin-user-doc --> CMP Field endTime Returns the endTime
    * @return the endTime <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getEndTime(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the endTime
    * @param java.lang.Integer the new endTime value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setEndTime( java.lang.Integer endTime ) ;

   /**
    * <!-- begin-user-doc --> CMP Field day Returns the day
    * @return the day <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.Integer getDay(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the day
    * @param java.lang.Integer the new day value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setDay( java.lang.Integer day ) ;

   /**
    * <!-- begin-user-doc --> CMP Field scheduleID Returns the scheduleID
    * @return the scheduleID <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String getScheduleID(  ) ;

   /**
    * <!-- begin-user-doc --> Sets the scheduleID
    * @param java.lang.String the new scheduleID value <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
    * @generated     */
   public void setScheduleID( java.lang.String scheduleID ) ;

}
